@extends('layouts.app')

@section('content')
@php
    $data = data_get($state ?? [], 'extracted', []);
    $fmt = \App\Support\UiFormatter::class;
    $companyId = auth()->user()->company_id;
    $clients = \App\Models\Client::query()->forCompany($companyId)->orderBy('legal_name')->get();
    $projects = \App\Models\Project::query()->forCompany($companyId)->orderBy('name')->get();
    $categories = \App\Models\ExpenseCategory::query()->forCompany($companyId)->orderBy('name')->get();
    $types = \App\Models\ExpenseType::query()->forCompany($companyId)->orderBy('name')->get();
    $documentTypes = \App\Models\DocumentType::query()->forCompany($companyId)->where('domain', 'expense')->orderBy('name')->get();
    $matchedType = $state ? app(\App\Services\ExpenseDocumentPdfImportService::class)->documentTypeMatch($companyId, $data['document_type'] ?? null) : null;
    $expected = $state && is_numeric($data['net_amount'] ?? null) && filled($data['issue_date'] ?? null) ? app(\App\Services\PayablesService::class)->amountsWithVat($companyId, $data['net_amount'], $data['issue_date'], false) : null;
    $currencyBlocked = filled($data['currency_code'] ?? null) && strtoupper((string) $data['currency_code']) !== 'CLP';
@endphp
<div class="page-header"><div><h1 class="page-title">Crear Gasto desde PDF</h1><div class="page-subtitle">Analice el documento, revise los datos y confirme el gasto por el flujo financiero normal.</div></div><a class="btn btn-outline-secondary" href="{{ route('expense-documents.index') }}">Volver</a></div>
@if (!$state)
<div class="app-panel p-3"><form method="POST" action="{{ route('expense-documents.from-pdf.analyze') }}" enctype="multipart/form-data" data-expense-pdf-analysis-form aria-busy="false">@csrf<label class="form-label" for="expense-pdf-file">Documento PDF</label><input id="expense-pdf-file" class="form-control" type="file" name="expense_pdf" accept="application/pdf,.pdf" required data-expense-pdf-file><div class="small text-muted mt-2">PDF privado de hasta 10 MB. Se realiza una sola llamada de análisis.</div><button class="btn btn-primary mt-3" type="submit" data-expense-pdf-submit><span data-expense-pdf-submit-label>Analizar documento</span></button><div class="alert alert-info mt-3 d-none" data-expense-pdf-progress aria-live="polite"><span class="spinner-border spinner-border-sm me-2" aria-hidden="true"></span>Analizando documento...<div class="progress mt-2" role="progressbar" aria-label="Análisis en curso"><div class="progress-bar progress-bar-striped progress-bar-animated" style="width:100%"></div></div></div></form></div>
@else
<form method="POST" action="{{ route('operational.store', 'expense-documents') }}" data-expense-pdf-form>@csrf<input type="hidden" name="expense_pdf_import_token" value="{{ $token }}">
<div class="row g-3"><div class="col-lg-7"><div class="app-panel p-3"><div class="section-title mb-3">Resumen detectado</div><dl class="row small mb-0"><dt class="col-sm-5">Proveedor</dt><dd class="col-sm-7">{{ $data['supplier_name'] ?? 'No informado' }}</dd><dt class="col-sm-5">RUT proveedor</dt><dd class="col-sm-7">{{ $data['supplier_tax_id'] ?? 'No informado' }}</dd><dt class="col-sm-5">Tipo documento</dt><dd class="col-sm-7">{{ $data['document_type'] ?? 'No identificado' }}</dd><dt class="col-sm-5">N° documento</dt><dd class="col-sm-7">{{ $data['document_number'] ?? 'No informado' }}</dd><dt class="col-sm-5">Fecha</dt><dd class="col-sm-7">{{ $data['issue_date'] ?? 'No informada' }}</dd><dt class="col-sm-5">Vencimiento</dt><dd class="col-sm-7">{{ $data['due_date'] ?? ($data['date_source'] === 'CALCULATED' ? 'Calculado' : 'No informado') }}</dd><dt class="col-sm-5">Moneda</dt><dd class="col-sm-7">{{ $data['currency_code'] ?? 'No informada' }}</dd><dt class="col-sm-5">Neto / IVA / Total PDF</dt><dd class="col-sm-7">{{ $fmt::formatMoney($data['net_amount'] ?? null, 'CLP') }} / {{ $fmt::formatMoney($data['vat_amount'] ?? null, 'CLP') }} / {{ $fmt::formatMoney($data['total_amount'] ?? null, 'CLP') }}</dd></dl>@if($currencyBlocked)<div class="alert alert-warning mt-3 mb-0">La moneda indicada es {{ $data['currency_code'] }}. La V1 solo crea documentos en CLP.</div>@endif</div>@if($expected)<div class="app-panel p-3 mt-3"><div class="section-title mb-2">Conciliación de importes</div><div class="small">Datos del PDF: Neto {{ $data['net_amount'] ?? '—' }} · IVA {{ $data['vat_amount'] ?? '—' }} · Total {{ $data['total_amount'] ?? '—' }}</div><div class="small">Cálculo TDAT: Neto {{ $expected['net_amount'] }} · IVA {{ $expected['vat_amount'] }} · Total {{ $expected['gross_amount'] }}</div>@if(is_numeric($data['vat_amount'] ?? null) && abs((float)$data['vat_amount'] - $expected['vat_amount']) > .01)<div class="alert alert-danger py-2 mt-2 mb-0">Los montos del PDF no coinciden con el cálculo vigente de TDAT. Revise el documento y los datos antes de continuar.</div>@else<div class="small text-success mt-2">Importes consistentes según el cálculo vigente.</div>@endif</div>@endif</div>
<div class="col-lg-5"><div class="app-panel p-3"><div class="section-title mb-3">Revisión y confirmación</div><div class="mb-2"><label class="form-label">Proveedor</label><input class="form-control" name="vendor_name" value="{{ old('vendor_name', $data['supplier_name'] ?? '') }}"></div><div class="mb-2"><label class="form-label">Tipo documento</label><select class="form-select" name="document_type_id"><option value="">Seleccione</option>@foreach($documentTypes as $type)<option value="{{ $type->id }}" @selected((string)old('document_type_id', $matchedType?->id) === (string)$type->id)>{{ $type->name }}</option>@endforeach</select></div><div class="mb-2"><label class="form-label">Cliente</label><select class="form-select" name="client_id"><option value="">Seleccione</option>@foreach($clients as $client)<option value="{{ $client->id }}">{{ $client->legal_name }}</option>@endforeach</select></div><div class="mb-2"><label class="form-label">Proyecto</label><select class="form-select" name="project_id"><option value="">Seleccione</option>@foreach($projects as $project)<option value="{{ $project->id }}">{{ $project->code }} — {{ $project->name }}</option>@endforeach</select></div><div class="mb-2"><label class="form-label">Categoría</label><select class="form-select" name="expense_category_id"><option value="">Seleccione</option>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select></div><div class="mb-2"><label class="form-label">Tipo gasto</label><select class="form-select" name="expense_type_id"><option value="">Seleccione</option>@foreach($types as $type)<option value="{{ $type->id }}">{{ $type->name }}</option>@endforeach</select></div><div class="row g-2"><div class="col"><label class="form-label">Fecha</label><input class="form-control" type="date" name="issue_date" required value="{{ old('issue_date', $data['issue_date'] ?? '') }}"></div><div class="col"><label class="form-label">Vencimiento</label><input class="form-control" type="date" name="due_date" value="{{ old('due_date', $data['due_date'] ?? '') }}"></div></div><div class="mb-2 mt-2"><label class="form-label">Neto CLP</label><input class="form-control" type="text" inputmode="numeric" data-clp-display required value="{{ $fmt::formatMoney(old('net_amount', $data['net_amount'] ?? null), 'CLP') }}"><input type="hidden" name="net_amount" data-clp-raw value="{{ old('net_amount', $data['net_amount'] ?? '') }}"></div><div class="form-check mb-3"><input class="form-check-input" type="checkbox" name="deductible_vat" value="1" id="deductible-vat"><label class="form-check-label" for="deductible-vat">IVA recuperable (decisión del usuario)</label></div><button class="btn btn-primary w-100" type="submit" @disabled($currencyBlocked)>Crear gasto y adjuntar PDF</button>@if($currencyBlocked)<div class="small text-warning mt-2">Resuelva la moneda antes de crear.</div>@endif</div></div></div></form>
@endif
@endsection
@push('scripts')<script nonce="{{ $cspNonce ?? '' }}">document.querySelectorAll('[data-clp-display]').forEach(i=>i.addEventListener('input',()=>{const d=i.value.replace(/\D/g,'');i.form.querySelector('[data-clp-raw]').value=d;i.value=d?new Intl.NumberFormat('es-CL').format(Number(d)):'';}));(()=>{const f=document.querySelector('[data-expense-pdf-analysis-form]');if(!f)return;f.addEventListener('submit',e=>{if(!f.checkValidity()||f.dataset.started)return;e.preventDefault();f.dataset.started='1';f.setAttribute('aria-busy','true');const b=f.querySelector('[data-expense-pdf-submit]'),p=f.querySelector('[data-expense-pdf-progress]');b.disabled=true;b.innerHTML='<span class="spinner-border spinner-border-sm me-1" aria-hidden="true"></span>Analizando documento...';p.classList.remove('d-none');f.submit();});})();</script>@endpush
