@extends('layouts.app')
@section('content')
@php($data=data_get($state ?? [],'extracted',[]))
<div class="page-header"><div><h1 class="page-title">{{ $item ? 'Adjuntar factura emitida PDF' : 'Crear Factura desde PDF' }}</h1><div class="page-subtitle">El cálculo contractual de TDAT siempre prevalece sobre el PDF.</div></div><a class="btn btn-outline-secondary" href="{{ route('sales-documents.index') }}">Volver</a></div>
@if(!$state)
<div class="app-panel p-3"><form method="POST" action="{{ route('sales-documents.from-pdf.analyze') }}" enctype="multipart/form-data" data-sales-pdf-analysis-form>
@csrf
@if($item)<input type="hidden" name="document_id" value="{{ $item->id }}">@endif
<label class="form-label">Factura PDF</label><input class="form-control" type="file" name="sales_pdf" accept="application/pdf,.pdf" required><button class="btn btn-primary mt-3" type="submit">Analizar factura</button><div class="alert alert-info d-none mt-3" data-sales-pdf-progress aria-live="polite"><span class="spinner-border spinner-border-sm me-2" aria-hidden="true"></span>Analizando factura...<div class="progress mt-2"><div class="progress-bar progress-bar-striped progress-bar-animated" style="width:100%"></div></div></div></form></div>
@else
@php($clients=\App\Models\Client::query()->forCompany(auth()->user()->company_id)->orderBy('legal_name')->get()) @php($types=\App\Models\DocumentType::query()->forCompany(auth()->user()->company_id)->where('domain','sales')->orderBy('name')->get()) @php($matchedClient=app(\App\Services\SalesDocumentPdfImportService::class)->matchClient(auth()->user()->company_id,$data['customer_tax_id']??null,$data['customer_name']??null)) @php($matchedType=app(\App\Services\SalesDocumentPdfImportService::class)->matchDocumentType(auth()->user()->company_id,$data['document_type']??null))
<div class="row g-3"><div class="col-lg-6"><div class="app-panel p-3"><div class="section-title mb-2">Factura PDF</div><dl class="row small mb-0"><dt class="col-5">Número</dt><dd class="col-7">{{ $data['document_number']??'No informado' }}</dd><dt class="col-5">Cliente</dt><dd class="col-7">{{ $data['customer_name']??'No informado' }}</dd><dt class="col-5">Fecha</dt><dd class="col-7">{{ $data['issue_date']??'No informada' }}</dd><dt class="col-5">Neto / IVA / Total</dt><dd class="col-7">{{ $data['net_amount']??'—' }} / {{ $data['vat_amount']??'—' }} / {{ $data['total_amount']??'—' }}</dd></dl></div>
@if($item)
@php($comparison=app(\App\Services\SalesDocumentPdfImportService::class)->compare($state,$item))
<div class="app-panel p-3 mt-3"><div class="section-title mb-2">Comparación contra factura TDAT</div><div class="small">Neto: {{ $comparison['net_amount']?'✓':'Revisar' }} · IVA: {{ $comparison['vat_amount']?'✓':'Revisar' }} · Total: {{ $comparison['total_amount']?'✓':'Revisar' }} · Fecha: {{ $comparison['issue_date']?'✓':'Revisar' }}</div>
@if(!$comparison['ok'])
<div class="alert alert-danger py-2 mt-2 mb-0">Los datos de la factura emitida no coinciden con el documento de TDAT. Revise antes de confirmar.</div>
@else
<div class="text-success small mt-2">Datos consistentes. El cálculo contractual se conservará.</div>
@endif
</div>
@endif
</div>
<div class="col-lg-6"><div class="app-panel p-3"><div class="section-title mb-2">Revisión</div>@if($item)<form method="POST" action="{{ route('operational.sales-documents.confirm',['sales-documents',$item->id]) }}">@csrf<input type="hidden" name="sales_pdf_import_token" value="{{ $token }}"><label class="form-label">N° documento</label><input class="form-control" name="document_number" value="{{ $data['document_number']??$item->document_number }}"><button class="btn btn-success mt-3" type="submit">Confirmar factura y adjuntar PDF</button></form>@else<form method="POST" action="{{ route('operational.store','sales-documents') }}">@csrf<input type="hidden" name="sales_pdf_import_token" value="{{ $token }}"><label class="form-label">Cliente</label><select class="form-select mb-2" name="client_id" required><option value="">Seleccione</option>@foreach($clients as $client)<option value="{{ $client->id }}" @selected($matchedClient?->id===$client->id)>{{ $client->legal_name }}</option>@endforeach</select><label class="form-label">Tipo documento</label><select class="form-select mb-2" name="document_type_id" required><option value="">Seleccione</option>@foreach($types as $type)<option value="{{ $type->id }}" @selected($matchedType?->id===$type->id)>{{ $type->name }}</option>@endforeach</select><label class="form-label">Fecha emisión</label><input class="form-control mb-2" type="date" name="issue_date" value="{{ $data['issue_date']??'' }}" required><label class="form-label">Neto</label><input class="form-control mb-2" type="number" step="1" name="net_amount" value="{{ $data['net_amount']??'' }}" required><label class="form-label">Vencimiento</label><input class="form-control mb-2" type="date" name="due_date" value="{{ $data['due_date']??'' }}"><button class="btn btn-primary mt-2" type="submit">Crear factura y adjuntar PDF</button></form>@endif</div></div></div>
@endif
@endsection
@push('scripts')<script nonce="{{ $cspNonce ?? '' }}">(()=>{const f=document.querySelector('[data-sales-pdf-analysis-form]');if(!f)return;f.addEventListener('submit',e=>{if(f.dataset.started||!f.checkValidity())return;e.preventDefault();f.dataset.started='1';f.setAttribute('aria-busy','true');const b=f.querySelector('button[type=submit]');b.disabled=true;b.innerHTML='<span class="spinner-border spinner-border-sm me-1" aria-hidden="true"></span>Analizando factura...';f.querySelector('[data-sales-pdf-progress]').classList.remove('d-none');f.submit();});})();</script>@endpush
