<?php

return [
    ['id' => 'GLOBAL-READONLY-001', 'module' => 'global', 'type' => 'DEFINED', 'title' => 'Ayudante sin operaciones', 'content' => 'El ayudante explica información disponible, no crea, modifica ni guarda registros.', 'keywords' => ['ayudante', 'guardar', 'crear', 'modificar'], 'source' => 'Assistant V1'],
    ['id' => 'GLOBAL-CATALOG-001', 'module' => 'global', 'type' => 'REQUIRED', 'title' => 'Catálogos y datos obligatorios', 'content' => 'Los campos obligatorios requieren información del usuario y los catálogos solo permiten valores existentes.', 'keywords' => ['obligatorio', 'catálogo', 'seleccionar', 'ingresar'], 'source' => 'config/operational.php'],
    ['id' => 'GLOBAL-READONLY-002', 'module' => 'global', 'type' => 'DEFINED', 'title' => 'Campos calculados', 'content' => 'Los campos de solo lectura son calculados o controlados por el sistema.', 'keywords' => ['solo lectura', 'calculado', 'readonly'], 'source' => 'config/operational.php'],
    ['id' => 'CLIENT-PAYMENT-001', 'module' => 'clients', 'type' => 'DEFINED', 'title' => 'Condición de pago cliente', 'content' => 'La condición de pago del cliente puede utilizarse cuando el proyecto no tiene una condición propia.', 'keywords' => ['cliente', 'condición', 'pago', 'vencimiento'], 'source' => 'ProjectBillingMilestoneService'],
    ['id' => 'PROJECT-CURRENCY-001', 'module' => 'projects', 'type' => 'DEFINED', 'title' => 'Moneda y venta contractual', 'content' => 'La venta neta y la tarifa comercial se interpretan en la moneda comercial definida por el proyecto.', 'keywords' => ['proyecto', 'moneda', 'venta neta', 'tarifa'], 'source' => 'docs/domain-contract.md'],
    ['id' => 'PROJECT-CLOSED-001', 'module' => 'projects', 'type' => 'DEFINED', 'title' => 'Proyecto cerrado', 'content' => 'Un Proyecto cerrado se factura mediante su plan de hitos porcentuales.', 'keywords' => ['proyecto cerrado', 'hito', 'factura'], 'source' => 'BillingStrategyService'],
    ['id' => 'PROJECT-HOURLY-001', 'module' => 'projects', 'type' => 'DEFINED', 'title' => 'Proyecto por hora', 'content' => 'Un proyecto Por Hora se factura con HH aprobadas aún no facturadas y la tarifa comercial del proyecto.', 'keywords' => ['por hora', 'hh', 'horas aprobadas', 'tarifa comercial'], 'source' => 'SalesPrefacturationService'],
    ['id' => 'PROJECT-COST-001', 'module' => 'projects', 'type' => 'DEFINED', 'title' => 'Tarifa comercial y costo', 'content' => 'La tarifa comercial del proyecto no corresponde al valor HH de costeo de Persona o Asignación.', 'keywords' => ['tarifa comercial', 'costo', 'asignación', 'persona'], 'source' => 'docs/domain-contract.md'],
    ['id' => 'TIME-APPROVAL-001', 'module' => 'time-entries', 'type' => 'DEFINED', 'title' => 'Horas aprobadas', 'content' => 'Las horas aprobadas no pueden exceder las horas trabajadas y son las elegibles para los flujos que las consumen.', 'keywords' => ['horas', 'trabajadas', 'aprobadas'], 'source' => 'docs/domain-contract.md'],
    ['id' => 'SALES-MILESTONE-001', 'module' => 'sales-documents', 'type' => 'DEFINED', 'title' => 'Factura por hito', 'content' => 'Una factura PROJECT_MILESTONE se genera desde un hito pendiente y no se duplica mientras exista una factura activa del hito.', 'keywords' => ['factura', 'hito', 'borrador', 'duplicar'], 'source' => 'ProjectBillingMilestoneService'],
    ['id' => 'SALES-TIME-001', 'module' => 'sales-documents', 'type' => 'DEFINED', 'title' => 'Factura por horas', 'content' => 'Una factura TIME_ENTRIES utiliza HH aprobadas no facturadas; las HH ya vinculadas a una factura activa no se reutilizan.', 'keywords' => ['factura', 'horas', 'time entries', 'facturadas'], 'source' => 'SalesPrefacturationService'],
    ['id' => 'SALES-DATES-001', 'module' => 'sales-documents', 'type' => 'DEFINED', 'title' => 'Fechas de facturación', 'content' => 'La fecha prevista es un pronóstico distinto de la fecha real de emisión; la emisión no puede tener fecha futura.', 'keywords' => ['fecha prevista', 'fecha emisión', 'futura'], 'source' => 'BillingDateRulesTest'],
    ['id' => 'SALES-DUE-001', 'module' => 'sales-documents', 'type' => 'CALCULATED', 'title' => 'Vencimiento y cobro proyectado', 'content' => 'El vencimiento se calcula desde la fecha de emisión y la condición de pago efectiva cuando está configurada.', 'keywords' => ['vencimiento', 'cobro proyectado', 'condición pago'], 'source' => 'ProjectBillingMilestoneService'],
    ['id' => 'RECEIVABLES-001', 'module' => 'sales-documents', 'type' => 'DEFINED', 'title' => 'Cuentas por cobrar', 'content' => 'Los documentos borrador, anulados o pagados no se tratan como saldos pendientes cobrables.', 'keywords' => ['por cobrar', 'saldo', 'pagado', 'anulado', 'borrador'], 'source' => 'ReceivablesService'],
    ['id' => 'EXPENSE-IVA-001', 'module' => 'expense-documents', 'type' => 'DEFINED', 'title' => 'Gastos e IVA', 'content' => 'La categoría, subcategoría y tratamiento de IVA se definen en el documento de gasto y sus catálogos.', 'keywords' => ['gasto', 'categoría', 'subcategoría', 'iva'], 'source' => 'config/operational.php'],
    ['id' => 'TREASURY-CASH-001', 'module' => 'cash-movements', 'type' => 'DEFINED', 'title' => 'Movimientos de caja', 'content' => 'Un movimiento Borrador no equivale a caja real; un movimiento Contabilizado participa en los flujos autorizados.', 'keywords' => ['tesorería', 'caja', 'borrador', 'contabilizado'], 'source' => 'CashMovementService'],
    ['id' => 'TREASURY-RECONCILIATION-001', 'module' => 'cash-accounts', 'type' => 'DEFINED', 'title' => 'Conciliación bancaria', 'content' => 'La conciliación usa una cuenta activa CLP, saldo inicial, fecha de saldo inicial, saldo sistema y saldo banco; no modifica movimientos para hacer cuadrar.', 'keywords' => ['conciliación', 'saldo inicial', 'saldo sistema', 'saldo banco'], 'source' => 'BankReconciliationService'],
    ['id' => 'BANK-STATEMENT-001', 'module' => 'bank-statements', 'type' => 'DEFINED', 'title' => 'Cartolas y matching', 'content' => 'Una sugerencia de matching no confirma una operación. Ignorar o revertir requiere trazabilidad y motivo.', 'keywords' => ['cartola', 'matching', 'ignorar', 'revertir'], 'source' => 'BankStatementMatchingService'],
    ['id' => 'PAYROLL-001', 'module' => 'payroll-records', 'type' => 'DEFINED', 'title' => 'Remuneraciones', 'content' => 'Los valores calculados de remuneración no se inventan; los overrides requieren un dato explícito y trazable.', 'keywords' => ['remuneración', 'override', 'calculado'], 'source' => 'docs/domain-contract.md'],
    ['id' => 'MANAGEMENT-001', 'module' => 'management', 'type' => 'DEFINED', 'title' => 'Gestión financiera', 'content' => 'Presupuesto, rentabilidad, compromisos y flujo de caja son conceptos distintos y no deben mezclarse.', 'keywords' => ['presupuesto', 'rentabilidad', 'flujo de caja', 'cockpit'], 'source' => 'docs/domain-contract.md'],
];
