<?php

use App\Models\Activity;
use App\Models\Afp;
use App\Models\ApprovalStatus;
use App\Models\Bank;
use App\Models\BankAccountType;
use App\Models\Budget;
use App\Models\CashAccount;
use App\Models\CashMovement;
use App\Models\CashMovementType;
use App\Models\Client;
use App\Models\ClientType;
use App\Models\ContractType;
use App\Models\CostCenter;
use App\Models\Currency;
use App\Models\DocumentType;
use App\Models\EmploymentMode;
use App\Models\ExchangeRate;
use App\Models\ExpenseCategory;
use App\Models\ExpenseDocument;
use App\Models\ExpenseSubcategory;
use App\Models\ExpenseType;
use App\Models\HealthSystem;
use App\Models\IncomeTaxBracket;
use App\Models\LegalOrganization;
use App\Models\LegalObligation;
use App\Models\LegalParameter;
use App\Models\ObligationType;
use App\Models\OccupationalInsuranceEntity;
use App\Models\PaymentMethod;
use App\Models\PaymentTerm;
use App\Models\PayrollAdjustment;
use App\Models\PayrollRecord;
use App\Models\Person;
use App\Models\Position;
use App\Models\Project;
use App\Models\ProjectAssignment;
use App\Models\ProjectManager;
use App\Models\ProjectType;
use App\Models\RecordStatus;
use App\Models\SalesDocument;
use App\Models\Scenario;
use App\Models\TaxRegime;
use App\Models\TimeEntry;
use App\Models\UfValue;
use App\Models\UtmValue;
use App\Models\CompanySetting;
use App\Models\AfpRate;

$catalogBaseRules = [
    'code' => ['required', 'string', 'max:80'],
    'name' => ['required', 'string', 'max:255'],
    'description' => ['nullable', 'string'],
    'active' => ['nullable', 'boolean'],
    'sort_order' => ['nullable', 'integer', 'min:0'],
];

return [
    'clients' => [
        'title' => 'Clientes',
        'section' => 'Operación',
        'model' => Client::class,
        'display' => 'legal_name',
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'legal_name' => ['label' => 'Razon social', 'type' => 'text'],
            'tax_id' => ['label' => 'RUT', 'type' => 'text', 'presentation' => 'rut'],
            'client_type_id' => ['label' => 'Tipo cliente', 'type' => 'relation', 'model' => ClientType::class, 'display' => 'name'],
            'contact_name' => ['label' => 'Contacto', 'type' => 'text'],
            'contact_email' => ['label' => 'Correo', 'type' => 'email'],
            'payment_term_id' => ['label' => 'Condición de pago', 'type' => 'relation', 'model' => PaymentTerm::class, 'display' => 'name'],
            'client_status_id' => ['label' => 'Estado', 'type' => 'relation', 'model' => RecordStatus::class, 'display' => 'name', 'where' => ['domain' => 'client']],
            'notes' => ['label' => 'Notas', 'type' => 'textarea'],
        ],
        'rules' => [
            'code' => ['required', 'string', 'max:40'],
            'legal_name' => ['required', 'string', 'max:255'],
            'tax_id' => ['nullable', 'string', 'max:30'],
            'client_type_id' => ['nullable', 'integer'],
            'contact_name' => ['nullable', 'string', 'max:255'],
            'contact_email' => ['nullable', 'email', 'max:255'],
            'payment_term_id' => ['nullable', 'integer'],
            'client_status_id' => ['required', 'integer'],
            'notes' => ['nullable', 'string'],
        ],
    ],
    'projects' => [
        'title' => 'Proyectos',
        'section' => 'Operación',
        'model' => Project::class,
        'display' => 'name',
        'vigent_status_codes' => ['active', 'EN_EJECUCION'],
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'client_id' => ['label' => 'Cliente', 'type' => 'relation', 'model' => Client::class, 'display' => 'legal_name'],
            'sales_currency_id' => ['label' => 'Moneda de venta', 'type' => 'relation', 'model' => Currency::class, 'display' => 'name', 'section' => 'Comercial'],
            'name' => ['label' => 'Proyecto/Servicio', 'type' => 'text'],
            'project_type_id' => ['label' => 'Tipo proyecto', 'type' => 'relation', 'model' => ProjectType::class, 'display' => 'name'],
            'manager_id' => ['label' => 'Responsable', 'type' => 'relation', 'model' => ProjectManager::class, 'display' => 'name'],
            'start_date' => ['label' => 'Fecha inicio', 'type' => 'date'],
            'end_date' => ['label' => 'Fecha termino', 'type' => 'date'],
            'contract_type_id' => ['label' => 'Tipo contrato', 'type' => 'relation', 'model' => ContractType::class, 'display' => 'name', 'where' => ['domain' => 'commercial']],
            'payment_term_id' => ['label' => 'Forma/condición pago', 'type' => 'relation', 'model' => PaymentTerm::class, 'display' => 'name'],
            'sale_net' => ['label' => 'Venta neta', 'type' => 'money', 'currency_field' => 'sales_currency_display_currency', 'section' => 'Comercial'],
            'vat_rate' => ['label' => 'IVA', 'type' => 'decimal', 'presentation' => 'percent', 'readonly' => true, 'section' => 'Comercial'],
            'sale_total' => ['label' => 'Venta total', 'type' => 'money', 'currency_field' => 'sales_currency_display_currency', 'readonly' => true, 'section' => 'Comercial'],
            'project_status_id' => ['label' => 'Estado proyecto', 'type' => 'relation', 'model' => RecordStatus::class, 'display' => 'name', 'where' => ['domain' => 'project']],
            'billing_status_id' => ['label' => 'Estado facturacion', 'type' => 'relation', 'model' => RecordStatus::class, 'display' => 'name', 'where' => ['domain' => 'billing']],
        ],
        'rules' => [
            'code' => ['required', 'string', 'max:40'],
            'client_id' => ['required', 'integer', 'exists:clients,id'],
            'sales_currency_id' => ['nullable', 'integer'],
            'name' => ['required', 'string', 'max:255'],
            'project_type_id' => ['nullable', 'integer'],
            'manager_id' => ['nullable', 'integer'],
            'start_date' => ['nullable', 'date'],
            'end_date' => ['nullable', 'date', 'after_or_equal:start_date'],
            'contract_type_id' => ['nullable', 'integer'],
            'payment_term_id' => ['nullable', 'integer'],
            'sale_net' => ['nullable', 'numeric', 'min:0'],
            'vat_rate' => ['nullable', 'numeric', 'min:0'],
            'sale_total' => ['nullable', 'numeric', 'min:0'],
            'project_status_id' => ['required', 'integer'],
            'billing_status_id' => ['required', 'integer'],
        ],
    ],
    'people' => [
        'title' => 'Personal',
        'section' => 'Operación',
        'model' => Person::class,
        'display' => 'full_name',
        'index_fields' => [
            'rut' => ['label' => 'RUT', 'type' => 'text', 'presentation' => 'rut'],
            'full_name' => ['label' => 'Nombre completo', 'type' => 'text', 'sort_columns' => ['paternal_surname', 'maternal_surname', 'first_names']],
            'position_id' => ['label' => 'Cargo', 'type' => 'relation', 'model' => Position::class, 'display' => 'name'],
            'employment_mode_id' => ['label' => 'Modalidad', 'type' => 'relation', 'model' => EmploymentMode::class, 'display' => 'name'],
            'current_assignment_label' => ['label' => 'Proyecto / Asignación', 'type' => 'text'],
            'phone_number' => ['label' => 'Teléfono', 'type' => 'text', 'presentation' => 'phone'],
            'email' => ['label' => 'Correo', 'type' => 'email'],
            'worker_status_id' => ['label' => 'Estado', 'type' => 'relation', 'model' => RecordStatus::class, 'display' => 'name', 'where' => ['domain' => 'worker']],
        ],
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'first_names' => ['label' => 'Nombres', 'type' => 'text', 'section' => 'Datos personales', 'col' => 'col-12 col-md-6 col-xl-4'],
            'paternal_surname' => ['label' => 'Apellido paterno', 'type' => 'text', 'section' => 'Datos personales', 'col' => 'col-12 col-md-6 col-xl-4'],
            'maternal_surname' => ['label' => 'Apellido materno', 'type' => 'text', 'section' => 'Datos personales', 'col' => 'col-12 col-md-6 col-xl-4'],
            'rut' => ['label' => 'RUT', 'type' => 'text', 'section' => 'Datos personales', 'presentation' => 'rut', 'col' => 'col-12 col-md-6 col-xl-4'],
            'birth_date' => ['label' => 'Fecha nacimiento', 'type' => 'date', 'section' => 'Datos personales', 'col' => 'col-12 col-md-6 col-xl-4'],
            'nationality' => ['label' => 'Nacionalidad', 'type' => 'text', 'section' => 'Datos personales', 'col' => 'col-12 col-md-6 col-xl-4'],
            'email' => ['label' => 'Correo', 'type' => 'email', 'section' => 'Contacto', 'col' => 'col-12 col-md-6 col-xl-4'],
            'phone_country_code' => ['label' => 'Código país', 'type' => 'text', 'section' => 'Contacto', 'col' => 'col-12 col-md-6 col-xl-3'],
            'phone_number' => ['label' => 'Teléfono', 'type' => 'text', 'section' => 'Contacto', 'presentation' => 'phone', 'col' => 'col-12 col-md-6 col-xl-4'],
            'secondary_phone' => ['label' => 'Teléfono alternativo', 'type' => 'text', 'section' => 'Contacto', 'presentation' => 'phone', 'col' => 'col-12 col-md-6 col-xl-4'],
            'region_id' => ['label' => 'Región', 'type' => 'relation', 'model' => \App\Models\Region::class, 'display' => 'name', 'section' => 'Dirección', 'global' => true, 'col' => 'col-12 col-md-6 col-xl-4'],
            'commune_id' => ['label' => 'Comuna', 'type' => 'relation', 'model' => \App\Models\Commune::class, 'display' => 'name', 'section' => 'Dirección', 'global' => true, 'depends_on' => 'region_id', 'option_parent_key' => 'region_id', 'col' => 'col-12 col-md-6 col-xl-4'],
            'address_street' => ['label' => 'Calle', 'type' => 'text', 'section' => 'Dirección', 'col' => 'col-12 col-md-8'],
            'address_number' => ['label' => 'Número', 'type' => 'text', 'section' => 'Dirección', 'col' => 'col-12 col-md-4 col-xl-2'],
            'address_unit' => ['label' => 'Depto/Oficina', 'type' => 'text', 'section' => 'Dirección', 'col' => 'col-12 col-md-6 col-xl-3'],
            'postal_code' => ['label' => 'Código postal', 'type' => 'text', 'section' => 'Dirección', 'col' => 'col-12 col-md-6 col-xl-3'],
            'address_reference' => ['label' => 'Referencia', 'type' => 'textarea', 'section' => 'Dirección', 'col' => 'col-12'],
            'position_id' => ['label' => 'Cargo', 'type' => 'relation', 'model' => Position::class, 'display' => 'name', 'section' => 'Datos laborales', 'col' => 'col-12 col-md-6 col-xl-4'],
            'employment_mode_id' => ['label' => 'Modalidad', 'type' => 'relation', 'model' => EmploymentMode::class, 'display' => 'name', 'section' => 'Datos laborales', 'col' => 'col-12 col-md-6 col-xl-4'],
            'employment_contract_type_id' => ['label' => 'Tipo contrato', 'type' => 'relation', 'model' => ContractType::class, 'display' => 'name', 'where' => ['domain' => 'employment'], 'section' => 'Datos laborales', 'col' => 'col-12 col-md-6 col-xl-4'],
            'afp_id' => ['label' => 'AFP', 'type' => 'relation', 'model' => Afp::class, 'display' => 'name', 'active_column' => 'is_active', 'section' => 'Datos laborales', 'col' => 'col-12 col-md-6 col-xl-4'],
            'health_system_id' => ['label' => 'Sistema de salud', 'type' => 'relation', 'model' => HealthSystem::class, 'display' => 'name', 'relation_name' => 'healthSystemCatalog', 'section' => 'Datos laborales', 'col' => 'col-12 col-md-6 col-xl-4'],
            'monthly_value' => ['label' => 'Valor mensual', 'type' => 'money', 'section' => 'Datos laborales', 'col' => 'col-12 col-md-6 col-xl-4'],
            'hourly_rate_unit_type' => ['label' => 'Unidad valor HH', 'type' => 'select', 'options' => ['UF' => 'UF', 'CURRENCY' => 'Moneda'], 'section' => 'Datos laborales', 'col' => 'col-12 col-md-6 col-xl-3'],
            'hourly_rate_currency_id' => ['label' => 'Moneda valor HH', 'type' => 'relation', 'model' => Currency::class, 'display' => 'name', 'section' => 'Datos laborales', 'col' => 'col-12 col-md-6 col-xl-3'],
            'hourly_value' => ['label' => 'Valor HH', 'type' => 'money', 'currency_field' => 'hourly_rate_display_currency', 'section' => 'Datos laborales', 'col' => 'col-12 col-md-6 col-xl-4'],
            'monthly_hours' => ['label' => 'Horas mensuales', 'type' => 'number', 'presentation' => 'hours', 'section' => 'Datos laborales', 'col' => 'col-12 col-md-6 col-xl-3'],
            'worker_status_id' => ['label' => 'Estado', 'type' => 'relation', 'model' => RecordStatus::class, 'display' => 'name', 'where' => ['domain' => 'worker'], 'section' => 'Datos laborales', 'col' => 'col-12 col-md-6 col-xl-3'],
            'start_date' => ['label' => 'Fecha inicio', 'type' => 'date', 'section' => 'Datos laborales', 'col' => 'col-12 col-md-6 col-xl-3'],
            'end_date' => ['label' => 'Fecha termino', 'type' => 'date', 'section' => 'Datos laborales', 'col' => 'col-12 col-md-6 col-xl-3'],
            'bank_id' => ['label' => 'Banco', 'type' => 'relation', 'model' => Bank::class, 'display' => 'name', 'section' => 'Datos bancarios', 'col' => 'col-12 col-md-6 col-xl-4'],
            'bank_account_type_id' => ['label' => 'Tipo cuenta', 'type' => 'relation', 'model' => BankAccountType::class, 'display' => 'name', 'section' => 'Datos bancarios', 'col' => 'col-12 col-md-6 col-xl-4'],
            'bank_account_number' => ['label' => 'Número cuenta', 'type' => 'text', 'section' => 'Datos bancarios', 'col' => 'col-12 col-md-6 col-xl-4'],
            'bank_account_holder_rut' => ['label' => 'RUT titular cuenta', 'type' => 'text', 'section' => 'Datos bancarios', 'presentation' => 'rut', 'col' => 'col-12 col-md-6 col-xl-4'],
            'emergency_contact_name' => ['label' => 'Nombre contacto', 'type' => 'text', 'section' => 'Emergencia', 'col' => 'col-12 col-md-6 col-xl-4'],
            'emergency_contact_relationship' => ['label' => 'Relación', 'type' => 'text', 'section' => 'Emergencia', 'col' => 'col-12 col-md-6 col-xl-4'],
            'emergency_contact_phone' => ['label' => 'Teléfono', 'type' => 'text', 'section' => 'Emergencia', 'presentation' => 'phone', 'col' => 'col-12 col-md-6 col-xl-4'],
        ],
        'rules' => [
            'code' => ['required', 'string', 'max:40'],
            'first_names' => ['required', 'string', 'max:255'],
            'paternal_surname' => ['required', 'string', 'max:255'],
            'maternal_surname' => ['nullable', 'string', 'max:255'],
            'rut' => ['nullable', 'string', 'max:20'],
            'birth_date' => ['nullable', 'date'],
            'nationality' => ['nullable', 'string', 'max:120'],
            'email' => ['nullable', 'email', 'max:255'],
            'phone_country_code' => ['nullable', 'string', 'max:8'],
            'phone_number' => ['nullable', 'string', 'max:30'],
            'secondary_phone' => ['nullable', 'string', 'max:30'],
            'region_id' => ['nullable', 'integer'],
            'commune_id' => ['nullable', 'integer'],
            'address_street' => ['nullable', 'string', 'max:255'],
            'address_number' => ['nullable', 'string', 'max:30'],
            'address_unit' => ['nullable', 'string', 'max:80'],
            'postal_code' => ['nullable', 'string', 'max:20'],
            'address_reference' => ['nullable', 'string'],
            'position_id' => ['nullable', 'integer'],
            'employment_mode_id' => ['required', 'integer'],
            'employment_contract_type_id' => ['nullable', 'integer'],
            'afp_id' => ['nullable', 'integer'],
            'health_system_id' => ['nullable', 'integer'],
            'monthly_value' => ['nullable', 'numeric', 'min:0'],
            'hourly_rate_unit_type' => ['nullable', 'in:UF,CURRENCY'],
            'hourly_rate_currency_id' => ['nullable', 'integer'],
            'hourly_value' => ['nullable', 'numeric', 'min:0'],
            'monthly_hours' => ['nullable', 'integer', 'min:0'],
            'worker_status_id' => ['required', 'integer'],
            'start_date' => ['nullable', 'date'],
            'end_date' => ['nullable', 'date', 'after_or_equal:start_date'],
            'bank_id' => ['nullable', 'integer'],
            'bank_account_type_id' => ['nullable', 'integer'],
            'bank_account_number' => ['nullable', 'string', 'max:60'],
            'bank_account_holder_rut' => ['nullable', 'string', 'max:20'],
            'emergency_contact_name' => ['nullable', 'string', 'max:255'],
            'emergency_contact_relationship' => ['nullable', 'string', 'max:120'],
            'emergency_contact_phone' => ['nullable', 'string', 'max:30'],
        ],
    ],
    'assignments' => [
        'title' => 'Asignaciones',
        'singular_title' => 'Asignación',
        'section' => 'Operación',
        'model' => ProjectAssignment::class,
        'display' => 'code',
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text', 'col' => 'col-12 col-md-6 col-xl-3'],
            'person_id' => ['label' => 'Persona', 'type' => 'relation', 'model' => Person::class, 'display' => 'name', 'col' => 'col-12 col-md-6 col-xl-4'],
            'client_id' => ['label' => 'Cliente', 'type' => 'relation', 'model' => Client::class, 'display' => 'legal_name', 'col' => 'col-12 col-md-6 col-xl-4'],
            'project_id' => ['label' => 'Proyecto', 'type' => 'relation', 'model' => Project::class, 'display' => 'name', 'depends_on' => 'client_id', 'option_parent_key' => 'client_id', 'col' => 'col-12 col-md-6 col-xl-4'],
            'hourly_rate_unit_type' => ['label' => 'Unidad del valor HH', 'type' => 'select', 'options' => ['UF' => 'UF', 'CURRENCY' => 'Moneda'], 'col' => 'col-12 col-md-6 col-xl-3'],
            'hourly_rate_currency_id' => ['label' => 'Moneda valor HH', 'type' => 'relation', 'model' => Currency::class, 'display' => 'name', 'col' => 'col-12 col-md-6 col-xl-3'],
            'hourly_value' => ['label' => 'Valor HH', 'type' => 'money', 'currency_field' => 'hourly_rate_display_currency', 'col' => 'col-12 col-md-6 col-xl-3'],
            'project_value' => ['label' => 'Monto pactado de la asignación', 'type' => 'money', 'col' => 'col-12 col-md-6 col-xl-3', 'help' => 'Monto fijo pactado con esta persona por su participación en el proyecto. Se usa como base de remuneración cuando la modalidad es por proyecto. No corresponde al valor de venta del proyecto.'],
            'monthly_hours' => ['label' => 'Horas mensuales', 'type' => 'number', 'presentation' => 'hours', 'col' => 'col-12 col-md-6 col-xl-3'],
            'cost_center_id' => ['label' => 'Centro de costo', 'type' => 'relation', 'model' => CostCenter::class, 'display' => 'name', 'col' => 'col-12 col-md-6 col-xl-4'],
            'start_date' => ['label' => 'Fecha inicio', 'type' => 'date', 'col' => 'col-12 col-md-6 col-xl-3'],
            'end_date' => ['label' => 'Fecha término', 'type' => 'date', 'col' => 'col-12 col-md-6 col-xl-3'],
            'assignment_status_id' => ['label' => 'Estado', 'type' => 'relation', 'model' => RecordStatus::class, 'display' => 'name', 'where' => ['domain' => 'assignment'], 'col' => 'col-12 col-md-6 col-xl-3'],
        ],
        'rules' => [
            'code' => ['required', 'string', 'max:40'],
            'person_id' => ['required', 'integer', 'exists:people,id'],
            'client_id' => ['required', 'integer', 'exists:clients,id'],
            'project_id' => ['required', 'integer', 'exists:projects,id'],
            'hourly_rate_unit_type' => ['nullable', 'in:UF,CURRENCY'],
            'hourly_rate_currency_id' => ['nullable', 'integer'],
            'hourly_value' => ['nullable', 'numeric', 'min:0'],
            'project_value' => ['nullable', 'numeric', 'min:0'],
            'monthly_hours' => ['nullable', 'integer', 'min:0', 'max:744'],
            'cost_center_id' => ['nullable', 'integer'],
            'start_date' => ['nullable', 'date', 'required_with:end_date'],
            'end_date' => ['nullable', 'date', 'required_with:start_date', 'after_or_equal:start_date'],
            'assignment_status_id' => ['required', 'integer'],
        ],
    ],
    'time-entries' => [
        'title' => 'Horas',
        'singular_title' => 'Registro de horas',
        'create_title' => 'Registrar horas',
        'edit_title' => 'Editar registro de horas',
        'section' => 'Operación',
        'model' => TimeEntry::class,
        'display' => 'activity',
        'fields' => [
            'code' => ['label' => 'Código', 'type' => 'text', 'col' => 'col-12 col-md-6 col-xl-3'],
            'person_id' => ['label' => 'Persona', 'type' => 'relation', 'model' => Person::class, 'display' => 'name', 'col' => 'col-12 col-md-6 col-xl-4'],
            'entry_date' => ['label' => 'Fecha', 'type' => 'date', 'col' => 'col-12 col-md-6 col-xl-3'],
            'project_id' => ['label' => 'Proyecto', 'type' => 'relation', 'model' => Project::class, 'display' => 'name', 'col' => 'col-12 col-md-6 col-xl-4'],
            'client_id' => ['label' => 'Cliente', 'type' => 'relation', 'model' => Client::class, 'display' => 'legal_name', 'col' => 'col-12 col-md-6 col-xl-4'],
            'activity_id' => ['label' => 'Actividad', 'type' => 'relation', 'model' => Activity::class, 'display' => 'name', 'relation_name' => 'activityCatalog', 'col' => 'col-12 col-md-6 col-xl-4'],
            'hours_worked' => ['label' => 'Horas trabajadas', 'type' => 'decimal', 'presentation' => 'hours', 'col' => 'col-12 col-md-6 col-xl-3'],
            'hours_approved' => ['label' => 'Horas aprobadas', 'type' => 'decimal', 'presentation' => 'hours', 'col' => 'col-12 col-md-6 col-xl-3'],
            'hourly_value' => ['label' => 'Tarifa aplicable', 'type' => 'money', 'currency_field' => 'hourly_rate_display_currency', 'readonly' => true, 'col' => 'col-12 col-md-6 col-xl-4'],
            'cost_center_id' => ['label' => 'Centro de costo', 'type' => 'relation', 'model' => CostCenter::class, 'display' => 'name', 'col' => 'col-12 col-md-6 col-xl-4'],
            'approval_status_id' => ['label' => 'Aprobación', 'type' => 'relation', 'model' => ApprovalStatus::class, 'display' => 'name', 'col' => 'col-12 col-md-6 col-xl-3'],
            'payment_status' => ['label' => 'Pago', 'type' => 'select', 'options' => ['pending' => 'Pendiente', 'paid' => 'Pagado'], 'col' => 'col-12 col-md-6 col-xl-3'],
        ],
        'rules' => [
            'code' => ['required', 'string', 'max:40'],
            'entry_date' => ['required', 'date'],
            'person_id' => ['required', 'integer', 'exists:people,id'],
            'client_id' => ['nullable', 'integer', 'exists:clients,id'],
            'project_id' => ['required', 'integer', 'exists:projects,id'],
            'activity_id' => ['required', 'integer'],
            'hours_worked' => ['required', 'numeric', 'gt:0', 'max:24'],
            'hours_approved' => ['required', 'numeric', 'min:0', 'max:24'],
            'hourly_value' => ['nullable', 'numeric', 'min:0'],
            'cost_center_id' => ['nullable', 'integer'],
            'approval_status_id' => ['required', 'integer'],
            'payment_status' => ['required', 'string', 'max:20'],
        ],
    ],
    'sales-documents' => [
        'title' => 'Facturas/Ingresos',
        'section' => 'Ventas',
        'model' => SalesDocument::class,
        'display' => 'code',
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'client_id' => ['label' => 'Cliente', 'type' => 'relation', 'model' => Client::class, 'display' => 'legal_name'],
            'project_id' => ['label' => 'Proyecto', 'type' => 'relation', 'model' => Project::class, 'display' => 'name', 'depends_on' => 'client_id', 'option_parent_key' => 'client_id'],
            'document_type_id' => ['label' => 'Tipo documento', 'type' => 'relation', 'model' => DocumentType::class, 'display' => 'name', 'where' => ['domain' => 'sales']],
            'document_number' => ['label' => 'Numero', 'type' => 'text'],
            'issue_date' => ['label' => 'Fecha emision', 'type' => 'date'],
            'due_date' => ['label' => 'Fecha vencimiento', 'type' => 'date'],
            'projected_collection_date' => ['label' => 'Cobro proyectado', 'type' => 'date'],
            'payment_probability' => ['label' => 'Probabilidad', 'type' => 'decimal', 'presentation' => 'percent'],
            'net_amount' => ['label' => 'Neto', 'type' => 'money'],
            'vat_rate' => ['label' => 'IVA', 'type' => 'decimal', 'presentation' => 'percent', 'readonly' => true],
            'vat_amount' => ['label' => 'Monto IVA', 'type' => 'money', 'readonly' => true],
            'gross_amount' => ['label' => 'Total', 'type' => 'money', 'readonly' => true],
            'status' => ['label' => 'Estado', 'type' => 'text', 'readonly' => true],
            'is_voided' => ['label' => 'Anulado', 'type' => 'checkbox'],
        ],
        'rules' => [
            'code' => ['required', 'string', 'max:40'],
            'client_id' => ['required', 'integer', 'exists:clients,id'],
            'project_id' => ['nullable', 'integer', 'exists:projects,id'],
            'document_type_id' => ['required', 'integer'],
            'document_number' => ['nullable', 'string', 'max:60'],
            'issue_date' => ['required', 'date'],
            'due_date' => ['nullable', 'date'],
            'projected_collection_date' => ['nullable', 'date'],
            'payment_probability' => ['nullable', 'numeric', 'min:0', 'max:1'],
            'net_amount' => ['required', 'numeric', 'min:0'],
            'gross_amount' => ['nullable', 'numeric', 'min:0'],
            'is_voided' => ['nullable', 'boolean'],
        ],
    ],
    'expense-documents' => [
        'title' => 'Gastos/Egresos',
        'section' => 'Gastos',
        'model' => ExpenseDocument::class,
        'display' => 'code',
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'vendor_name' => ['label' => 'Proveedor', 'type' => 'text'],
            'client_id' => ['label' => 'Cliente', 'type' => 'relation', 'model' => Client::class, 'display' => 'legal_name'],
            'project_id' => ['label' => 'Proyecto', 'type' => 'relation', 'model' => Project::class, 'display' => 'name', 'depends_on' => 'client_id', 'option_parent_key' => 'client_id'],
            'expense_category_id' => ['label' => 'Categoria', 'type' => 'relation', 'model' => ExpenseCategory::class, 'display' => 'name'],
            'expense_subcategory_id' => ['label' => 'Subcategoria', 'type' => 'relation', 'model' => ExpenseSubcategory::class, 'display' => 'name', 'depends_on' => 'expense_category_id', 'option_parent_key' => 'expense_category_id'],
            'expense_type_id' => ['label' => 'Tipo gasto', 'type' => 'relation', 'model' => ExpenseType::class, 'display' => 'name', 'relation_name' => 'expenseType'],
            'document_type_id' => ['label' => 'Tipo documento', 'type' => 'relation', 'model' => DocumentType::class, 'display' => 'name', 'where' => ['domain' => 'expense']],
            'issue_date' => ['label' => 'Fecha documento', 'type' => 'date'],
            'due_date' => ['label' => 'Vencimiento', 'type' => 'date'],
            'net_amount' => ['label' => 'Neto', 'type' => 'money'],
            'vat_rate' => ['label' => 'IVA', 'type' => 'decimal', 'presentation' => 'percent', 'readonly' => true],
            'vat_amount' => ['label' => 'Monto IVA', 'type' => 'money', 'readonly' => true],
            'gross_amount' => ['label' => 'Total', 'type' => 'money', 'readonly' => true],
            'deductible_vat' => ['label' => 'IVA recuperable', 'type' => 'checkbox'],
            'payment_status' => ['label' => 'Estado', 'type' => 'text', 'readonly' => true],
        ],
        'rules' => [
            'code' => ['required', 'string', 'max:40'],
            'vendor_name' => ['nullable', 'string', 'max:255'],
            'client_id' => ['nullable', 'integer', 'exists:clients,id'],
            'project_id' => ['nullable', 'integer', 'exists:projects,id'],
            'expense_category_id' => ['nullable', 'integer'],
            'expense_subcategory_id' => ['nullable', 'integer'],
            'expense_type_id' => ['nullable', 'integer'],
            'document_type_id' => ['nullable', 'integer'],
            'issue_date' => ['required', 'date'],
            'due_date' => ['nullable', 'date'],
            'net_amount' => ['required', 'numeric', 'min:0'],
            'gross_amount' => ['nullable', 'numeric', 'min:0'],
            'deductible_vat' => ['nullable', 'boolean'],
        ],
    ],
    'cash-accounts' => [
        'title' => 'Cuentas de caja/banco',
        'section' => 'Tesorería',
        'model' => CashAccount::class,
        'display' => 'name',
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'name' => ['label' => 'Nombre', 'type' => 'text'],
            'bank_id' => ['label' => 'Banco', 'type' => 'relation', 'model' => Bank::class, 'display' => 'name'],
            'bank_account_type_id' => ['label' => 'Tipo cuenta', 'type' => 'relation', 'model' => BankAccountType::class, 'display' => 'name'],
            'currency_id' => ['label' => 'Moneda', 'type' => 'relation', 'model' => Currency::class, 'display' => 'name', 'relation_name' => 'currencyCatalog'],
            'opening_balance' => ['label' => 'Saldo inicial', 'type' => 'money', 'currency_relation' => 'currencyCatalog'],
            'is_active' => ['label' => 'Activa', 'type' => 'checkbox'],
        ],
        'rules' => [
            'code' => ['required', 'string', 'max:40'],
            'name' => ['required', 'string', 'max:255'],
            'bank_id' => ['nullable', 'integer'],
            'bank_account_type_id' => ['nullable', 'integer'],
            'currency_id' => ['required', 'integer'],
            'opening_balance' => ['required', 'numeric'],
            'is_active' => ['nullable', 'boolean'],
        ],
    ],
    'cash-movements' => [
        'title' => 'Movimientos de caja',
        'section' => 'Tesorería',
        'model' => CashMovement::class,
        'display' => 'code',
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'movement_type_id' => ['label' => 'Tipo movimiento', 'type' => 'relation', 'model' => CashMovementType::class, 'display' => 'name', 'relation_name' => 'movementType'],
            'source_document_type' => ['label' => 'Tipo documento origen', 'type' => 'select', 'options' => ['sales_document' => 'Factura/Ingreso', 'expense_document' => 'Gasto/Egreso', 'payroll_record' => 'Remuneracion', 'legal_obligation' => 'Obligacion', 'other' => 'Otro']],
            'source_document_code' => ['label' => 'Codigo documento', 'type' => 'text'],
            'counterparty_name' => ['label' => 'Contraparte', 'type' => 'text'],
            'project_id' => ['label' => 'Proyecto', 'type' => 'relation', 'model' => Project::class, 'display' => 'name'],
            'movement_date' => ['label' => 'Fecha', 'type' => 'date'],
            'income' => ['label' => 'Ingreso', 'type' => 'money'],
            'expense' => ['label' => 'Egreso', 'type' => 'money'],
            'payment_method_id' => ['label' => 'Medio pago', 'type' => 'relation', 'model' => PaymentMethod::class, 'display' => 'name'],
            'cash_account_id' => ['label' => 'Cuenta', 'type' => 'relation', 'model' => CashAccount::class, 'display' => 'name'],
            'reference' => ['label' => 'Referencia', 'type' => 'text'],
            'status' => ['label' => 'Estado', 'type' => 'select', 'options' => ['posted' => 'Contabilizado', 'voided' => 'Anulado']],
        ],
        'rules' => [
            'code' => ['required', 'string', 'max:40'],
            'movement_type_id' => ['required', 'integer'],
            'source_document_type' => ['nullable', 'string', 'max:40'],
            'source_document_code' => ['nullable', 'string', 'max:40'],
            'counterparty_name' => ['nullable', 'string', 'max:255'],
            'project_id' => ['nullable', 'integer', 'exists:projects,id'],
            'movement_date' => ['required', 'date'],
            'income' => ['nullable', 'numeric', 'min:0'],
            'expense' => ['nullable', 'numeric', 'min:0'],
            'payment_method_id' => ['nullable', 'integer'],
            'cash_account_id' => ['nullable', 'integer', 'exists:cash_accounts,id'],
            'reference' => ['nullable', 'string', 'max:255'],
            'status' => ['required', 'string', 'max:20'],
        ],
    ],
    'payroll-records' => [
        'title' => 'Remuneraciones',
        'singular_title' => 'Remuneración',
        'create_title' => 'Nueva remuneración',
        'edit_title' => 'Editar remuneración',
        'section' => 'Operación',
        'model' => PayrollRecord::class,
        'display' => 'code',
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text', 'readonly' => true],
            'person_id' => ['label' => 'Persona', 'type' => 'relation', 'model' => Person::class, 'display' => 'name'],
            'project_id' => ['label' => 'Proyecto', 'type' => 'relation', 'model' => Project::class, 'display' => 'name'],
            'period_date' => ['label' => 'Periodo', 'type' => 'date'],
            'payment_date' => ['label' => 'Fecha pago', 'type' => 'date'],
            'amount_basis' => ['label' => 'Base pactada', 'type' => 'select', 'options' => ['GROSS' => 'Bruto', 'NET' => 'Liquido pactado']],
            'hours_approved' => ['label' => 'Horas aprobadas', 'type' => 'number'],
            'monthly_value' => ['label' => 'Valor mensual override', 'type' => 'money'],
            'hourly_value' => ['label' => 'Valor hora override', 'type' => 'money'],
            'project_value' => ['label' => 'Valor proyecto/hito override', 'type' => 'money'],
            'bonuses' => ['label' => 'Bonos imponibles', 'type' => 'money'],
            'non_taxable_allowances' => ['label' => 'Asignaciones no imponibles', 'type' => 'money'],
            'advances' => ['label' => 'Anticipos', 'type' => 'money'],
            'other_deductions' => ['label' => 'Otros descuentos', 'type' => 'money'],
            'base_salary' => ['label' => 'Base calculada', 'type' => 'money', 'readonly' => true],
            'taxable_gross' => ['label' => 'Total imponible', 'type' => 'money', 'readonly' => true],
            'pension_health_base' => ['label' => 'Base AFP/salud', 'type' => 'money', 'readonly' => true],
            'afc_base' => ['label' => 'Base AFC', 'type' => 'money', 'readonly' => true],
            'employee_retention' => ['label' => 'Retencion honorarios', 'type' => 'money', 'readonly' => true],
            'afp_mandatory' => ['label' => 'AFP 10%', 'type' => 'money', 'readonly' => true],
            'afp_commission' => ['label' => 'Comision AFP', 'type' => 'money', 'readonly' => true],
            'health_employee' => ['label' => 'Salud trabajador', 'type' => 'money', 'readonly' => true],
            'afc_employee' => ['label' => 'AFC trabajador', 'type' => 'money', 'readonly' => true],
            'iusc_amount' => ['label' => 'Impuesto 2a categoria', 'type' => 'money', 'readonly' => true],
            'net_pay' => ['label' => 'Liquido', 'type' => 'money', 'readonly' => true],
            'afc_employer' => ['label' => 'AFC empleador', 'type' => 'money', 'readonly' => true],
            'employer_pension' => ['label' => 'Aporte previsional empleador', 'type' => 'money', 'readonly' => true],
            'accident_insurance' => ['label' => 'Ley 16.744', 'type' => 'money', 'readonly' => true],
            'sanna' => ['label' => 'SANNA', 'type' => 'money', 'readonly' => true],
            'vacation_provision_amount' => ['label' => 'Provision vacaciones', 'type' => 'money', 'readonly' => true],
            'employer_cost' => ['label' => 'Costo empresa', 'type' => 'money', 'readonly' => true],
            'calculation_status' => ['label' => 'Estado calculo', 'type' => 'text', 'readonly' => true],
            'calculation_notes' => ['label' => 'Observaciones calculo', 'type' => 'textarea', 'readonly' => true],
            'status' => ['label' => 'Estado pago', 'type' => 'text', 'readonly' => true],
        ],
        'rules' => [
            'person_id' => ['required', 'integer', 'exists:people,id'],
            'project_id' => ['nullable', 'integer', 'exists:projects,id'],
            'period_date' => ['required', 'date'],
            'payment_date' => ['nullable', 'date'],
            'amount_basis' => ['nullable', 'in:GROSS,NET'],
            'hours_approved' => ['nullable', 'numeric', 'min:0'],
            'monthly_value' => ['nullable', 'numeric', 'min:0'],
            'hourly_value' => ['nullable', 'numeric', 'min:0'],
            'project_value' => ['nullable', 'numeric', 'min:0'],
            'bonuses' => ['nullable', 'numeric', 'min:0'],
            'non_taxable_allowances' => ['nullable', 'numeric', 'min:0'],
            'advances' => ['nullable', 'numeric', 'min:0'],
            'other_deductions' => ['nullable', 'numeric', 'min:0'],
            'status' => ['nullable', 'string', 'max:20'],
        ],
    ],
    'payroll-adjustments' => [
        'title' => 'Novedades remuneración',
        'section' => 'Operación',
        'model' => PayrollAdjustment::class,
        'display' => 'type',
        'fields' => [
            'person_id' => ['label' => 'Persona', 'type' => 'relation', 'model' => Person::class, 'display' => 'name'],
            'period_date' => ['label' => 'Periodo', 'type' => 'date'],
            'type' => ['label' => 'Tipo', 'type' => 'select', 'options' => [
                'BONUS_TAXABLE' => 'Bono imponible',
                'NON_TAXABLE_ALLOWANCE' => 'Asignación no imponible',
                'ADVANCE' => 'Anticipo',
                'OTHER_DEDUCTION' => 'Otro descuento',
                'HOURS_APPROVED' => 'Horas aprobadas',
                'HEALTH_ADDITIONAL' => 'Salud adicional',
                'MONTHLY_VALUE' => 'Valor mensual override',
                'HOURLY_VALUE' => 'Valor hora override',
                'PROJECT_VALUE' => 'Valor proyecto/hito',
            ]],
            'amount' => ['label' => 'Monto', 'type' => 'money'],
            'quantity' => ['label' => 'Cantidad', 'type' => 'decimal'],
            'description' => ['label' => 'Descripción', 'type' => 'textarea'],
            'active' => ['label' => 'Activo', 'type' => 'checkbox'],
        ],
        'rules' => [
            'person_id' => ['required', 'integer', 'exists:people,id'],
            'period_date' => ['required', 'date'],
            'type' => ['required', 'string', 'in:BONUS_TAXABLE,NON_TAXABLE_ALLOWANCE,ADVANCE,OTHER_DEDUCTION,HOURS_APPROVED,HEALTH_ADDITIONAL,MONTHLY_VALUE,HOURLY_VALUE,PROJECT_VALUE'],
            'amount' => ['nullable', 'numeric', 'min:0'],
            'quantity' => ['nullable', 'numeric', 'min:0'],
            'description' => ['nullable', 'string'],
            'active' => ['nullable', 'boolean'],
        ],
    ],
    'legal-obligations' => [
        'title' => 'Obligaciones',
        'section' => 'Gestión',
        'model' => LegalObligation::class,
        'display' => 'code',
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'obligation_type_id' => ['label' => 'Tipo', 'type' => 'relation', 'model' => ObligationType::class, 'display' => 'name'],
            'organization_id' => ['label' => 'Organismo', 'type' => 'relation', 'model' => LegalOrganization::class, 'display' => 'name'],
            'period_date' => ['label' => 'Periodo', 'type' => 'date'],
            'due_date' => ['label' => 'Vencimiento', 'type' => 'date'],
            'estimated_amount' => ['label' => 'Estimado', 'type' => 'money'],
            'paid_amount' => ['label' => 'Pagado', 'type' => 'money', 'readonly' => true],
            'pending_amount' => ['label' => 'Pendiente', 'type' => 'money', 'readonly' => true],
            'status' => ['label' => 'Estado', 'type' => 'text', 'readonly' => true],
            'source_calculation' => ['label' => 'Fuente', 'type' => 'textarea'],
            'notes' => ['label' => 'Notas', 'type' => 'textarea'],
        ],
        'rules' => [
            'code' => ['required', 'string', 'max:40'],
            'obligation_type_id' => ['required', 'integer'],
            'organization_id' => ['nullable', 'integer'],
            'period_date' => ['required', 'date'],
            'due_date' => ['nullable', 'date'],
            'estimated_amount' => ['required', 'numeric', 'min:0'],
            'source_calculation' => ['nullable', 'string'],
            'notes' => ['nullable', 'string'],
        ],
    ],
    'budgets' => [
        'title' => 'Presupuestos',
        'section' => 'Gestión',
        'model' => Budget::class,
        'display' => 'period_date',
        'fields' => [
            'project_id' => ['label' => 'Proyecto', 'type' => 'relation', 'model' => Project::class, 'display' => 'name'],
            'scenario_id' => ['label' => 'Escenario', 'type' => 'relation', 'model' => Scenario::class, 'display' => 'name'],
            'period_date' => ['label' => 'Periodo', 'type' => 'date'],
            'revenue_budget' => ['label' => 'Ingreso presupuesto', 'type' => 'money'],
            'personnel_budget' => ['label' => 'Personal presupuesto', 'type' => 'money'],
            'other_direct_budget' => ['label' => 'Otros presupuesto', 'type' => 'money'],
            'legal_budget' => ['label' => 'Legal presupuesto', 'type' => 'money'],
            'other_indirect_budget' => ['label' => 'Indirectos presupuesto', 'type' => 'money'],
            'notes' => ['label' => 'Notas', 'type' => 'textarea'],
        ],
        'rules' => [
            'project_id' => ['nullable', 'integer', 'exists:projects,id'],
            'scenario_id' => ['nullable', 'integer', 'exists:scenarios,id'],
            'period_date' => ['required', 'date'],
            'revenue_budget' => ['required', 'numeric', 'min:0'],
            'personnel_budget' => ['required', 'numeric', 'min:0'],
            'other_direct_budget' => ['required', 'numeric', 'min:0'],
            'legal_budget' => ['required', 'numeric', 'min:0'],
            'other_indirect_budget' => ['required', 'numeric', 'min:0'],
            'notes' => ['nullable', 'string'],
        ],
    ],
    'scenarios' => [
        'title' => 'Escenarios',
        'section' => 'Gestión',
        'model' => Scenario::class,
        'display' => 'name',
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'name' => ['label' => 'Nombre', 'type' => 'text'],
            'sales_factor' => ['label' => 'Factor ventas', 'type' => 'decimal'],
            'cost_factor' => ['label' => 'Factor costos', 'type' => 'decimal'],
            'collection_delay_days' => ['label' => 'Retraso cobro dias', 'type' => 'number'],
            'new_hires_monthly' => ['label' => 'Nuevas contrataciones', 'type' => 'money'],
            'tariff_variation' => ['label' => 'Variacion tarifas', 'type' => 'decimal', 'presentation' => 'percent'],
            'description' => ['label' => 'Descripcion', 'type' => 'textarea'],
            'is_active' => ['label' => 'Activo', 'type' => 'checkbox'],
        ],
        'rules' => [
            'code' => ['required', 'string', 'max:40'],
            'name' => ['required', 'string', 'max:255'],
            'sales_factor' => ['required', 'numeric', 'min:0'],
            'cost_factor' => ['required', 'numeric', 'min:0'],
            'collection_delay_days' => ['required', 'integer'],
            'new_hires_monthly' => ['required', 'numeric'],
            'tariff_variation' => ['required', 'numeric'],
            'description' => ['nullable', 'string'],
            'is_active' => ['nullable', 'boolean'],
        ],
    ],
    'project-managers' => [
        'title' => 'Responsables',
        'section' => 'Administración',
        'breadcrumb_group' => 'Mantenedores',
        'model' => ProjectManager::class,
        'display' => 'name',
        'catalog' => true,
        'admin_only' => true,
        'usage' => [['model' => Project::class, 'column' => 'manager_id']],
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'name' => ['label' => 'Nombre', 'type' => 'text'],
            'description' => ['label' => 'Descripcion', 'type' => 'textarea'],
            'active' => ['label' => 'Activo', 'type' => 'checkbox'],
            'sort_order' => ['label' => 'Orden', 'type' => 'number'],
        ],
        'rules' => $catalogBaseRules,
    ],
    'cost-centers' => [
        'title' => 'Centros de costo',
        'section' => 'Administración',
        'breadcrumb_group' => 'Mantenedores',
        'model' => CostCenter::class,
        'display' => 'name',
        'catalog' => true,
        'admin_only' => true,
        'usage' => [
            ['model' => ProjectAssignment::class, 'column' => 'cost_center_id'],
            ['model' => TimeEntry::class, 'column' => 'cost_center_id'],
        ],
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'name' => ['label' => 'Nombre', 'type' => 'text'],
            'description' => ['label' => 'Descripcion', 'type' => 'textarea'],
            'active' => ['label' => 'Activo', 'type' => 'checkbox'],
            'sort_order' => ['label' => 'Orden', 'type' => 'number'],
        ],
        'rules' => $catalogBaseRules,
    ],
    'positions' => [
        'title' => 'Cargos',
        'section' => 'Administración',
        'breadcrumb_group' => 'Mantenedores',
        'model' => Position::class,
        'display' => 'name',
        'catalog' => true,
        'admin_only' => true,
        'usage' => [['model' => Person::class, 'column' => 'position_id']],
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'name' => ['label' => 'Nombre', 'type' => 'text'],
            'description' => ['label' => 'Descripcion', 'type' => 'textarea'],
            'active' => ['label' => 'Activo', 'type' => 'checkbox'],
            'sort_order' => ['label' => 'Orden', 'type' => 'number'],
        ],
        'rules' => $catalogBaseRules,
    ],
    'employment-modes' => [
        'title' => 'Modalidades',
        'section' => 'Administración',
        'breadcrumb_group' => 'Mantenedores',
        'model' => EmploymentMode::class,
        'display' => 'name',
        'catalog' => true,
        'admin_only' => true,
        'usage' => [['model' => Person::class, 'column' => 'employment_mode_id']],
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'name' => ['label' => 'Nombre', 'type' => 'text'],
            'description' => ['label' => 'Descripcion', 'type' => 'textarea'],
            'active' => ['label' => 'Activo', 'type' => 'checkbox'],
            'sort_order' => ['label' => 'Orden', 'type' => 'number'],
        ],
        'rules' => $catalogBaseRules,
    ],
    'contract-types' => [
        'title' => 'Tipos de contrato',
        'section' => 'Administración',
        'breadcrumb_group' => 'Mantenedores',
        'model' => ContractType::class,
        'display' => 'name',
        'catalog' => true,
        'admin_only' => true,
        'unique_scope' => ['domain'],
        'usage' => [
            ['model' => Person::class, 'column' => 'employment_contract_type_id'],
            ['model' => Project::class, 'column' => 'contract_type_id'],
        ],
        'fields' => [
            'domain' => ['label' => 'Dominio', 'type' => 'select', 'options' => ['employment' => 'Laboral', 'commercial' => 'Comercial']],
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'name' => ['label' => 'Nombre', 'type' => 'text'],
            'description' => ['label' => 'Descripcion', 'type' => 'textarea'],
            'active' => ['label' => 'Activo', 'type' => 'checkbox'],
            'sort_order' => ['label' => 'Orden', 'type' => 'number'],
        ],
        'rules' => array_merge($catalogBaseRules, ['domain' => ['required', 'string', 'in:employment,commercial']]),
    ],
    'banks' => [
        'title' => 'Bancos',
        'section' => 'Administración',
        'breadcrumb_group' => 'Mantenedores',
        'model' => Bank::class,
        'display' => 'name',
        'catalog' => true,
        'admin_only' => true,
        'usage' => [['model' => CashAccount::class, 'column' => 'bank_id']],
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'name' => ['label' => 'Nombre', 'type' => 'text'],
            'description' => ['label' => 'Descripcion', 'type' => 'textarea'],
            'active' => ['label' => 'Activo', 'type' => 'checkbox'],
            'sort_order' => ['label' => 'Orden', 'type' => 'number'],
        ],
        'rules' => $catalogBaseRules,
    ],
    'payment-methods' => [
        'title' => 'Medios de pago',
        'section' => 'Administración',
        'breadcrumb_group' => 'Mantenedores',
        'model' => PaymentMethod::class,
        'display' => 'name',
        'catalog' => true,
        'admin_only' => true,
        'usage' => [
            ['model' => CashMovement::class, 'column' => 'payment_method_id'],
            ['model' => PaymentTerm::class, 'column' => 'payment_method_id'],
        ],
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'name' => ['label' => 'Nombre', 'type' => 'text'],
            'description' => ['label' => 'Descripcion', 'type' => 'textarea'],
            'active' => ['label' => 'Activo', 'type' => 'checkbox'],
            'sort_order' => ['label' => 'Orden', 'type' => 'number'],
        ],
        'rules' => $catalogBaseRules,
    ],
    'expense-categories' => [
        'title' => 'Categorias de gasto',
        'section' => 'Administración',
        'breadcrumb_group' => 'Mantenedores',
        'model' => ExpenseCategory::class,
        'display' => 'name',
        'catalog' => true,
        'admin_only' => true,
        'usage' => [['model' => ExpenseDocument::class, 'column' => 'expense_category_id']],
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'name' => ['label' => 'Nombre', 'type' => 'text'],
            'description' => ['label' => 'Descripcion', 'type' => 'textarea'],
            'active' => ['label' => 'Activo', 'type' => 'checkbox'],
            'sort_order' => ['label' => 'Orden', 'type' => 'number'],
        ],
        'rules' => $catalogBaseRules,
    ],
    'expense-subcategories' => [
        'title' => 'Subcategorias de gasto',
        'section' => 'Administración',
        'breadcrumb_group' => 'Mantenedores',
        'model' => ExpenseSubcategory::class,
        'display' => 'name',
        'catalog' => true,
        'admin_only' => true,
        'unique_scope' => ['expense_category_id'],
        'usage' => [['model' => ExpenseDocument::class, 'column' => 'expense_subcategory_id']],
        'fields' => [
            'expense_category_id' => ['label' => 'Categoria', 'type' => 'relation', 'model' => ExpenseCategory::class, 'display' => 'name'],
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'name' => ['label' => 'Nombre', 'type' => 'text'],
            'description' => ['label' => 'Descripcion', 'type' => 'textarea'],
            'active' => ['label' => 'Activo', 'type' => 'checkbox'],
            'sort_order' => ['label' => 'Orden', 'type' => 'number'],
        ],
        'rules' => array_merge($catalogBaseRules, ['expense_category_id' => ['required', 'integer']]),
    ],
    'document-types' => [
        'title' => 'Tipos de documento',
        'section' => 'Administración',
        'breadcrumb_group' => 'Mantenedores',
        'model' => DocumentType::class,
        'display' => 'name',
        'catalog' => true,
        'admin_only' => true,
        'unique_scope' => ['domain'],
        'usage' => [
            ['model' => SalesDocument::class, 'column' => 'document_type_id'],
            ['model' => ExpenseDocument::class, 'column' => 'document_type_id'],
        ],
        'fields' => [
            'domain' => ['label' => 'Dominio', 'type' => 'select', 'options' => ['sales' => 'Ventas', 'expense' => 'Gastos']],
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'name' => ['label' => 'Nombre', 'type' => 'text'],
            'description' => ['label' => 'Descripcion', 'type' => 'textarea'],
            'active' => ['label' => 'Activo', 'type' => 'checkbox'],
            'sort_order' => ['label' => 'Orden', 'type' => 'number'],
        ],
        'rules' => array_merge($catalogBaseRules, ['domain' => ['required', 'string', 'in:sales,expense']]),
    ],
    'obligation-types' => [
        'title' => 'Tipos de obligación',
        'section' => 'Administración',
        'breadcrumb_group' => 'Mantenedores',
        'model' => ObligationType::class,
        'display' => 'name',
        'catalog' => true,
        'admin_only' => true,
        'usage' => [['model' => LegalObligation::class, 'column' => 'obligation_type_id']],
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'name' => ['label' => 'Nombre', 'type' => 'text'],
            'description' => ['label' => 'Descripcion', 'type' => 'textarea'],
            'active' => ['label' => 'Activo', 'type' => 'checkbox'],
            'sort_order' => ['label' => 'Orden', 'type' => 'number'],
        ],
        'rules' => $catalogBaseRules,
    ],
    'record-statuses' => [
        'title' => 'Estados principales',
        'section' => 'Administración',
        'breadcrumb_group' => 'Mantenedores',
        'model' => RecordStatus::class,
        'display' => 'name',
        'catalog' => true,
        'admin_only' => true,
        'unique_scope' => ['domain'],
        'usage' => [
            ['model' => Client::class, 'column' => 'client_status_id'],
            ['model' => Project::class, 'column' => 'project_status_id'],
            ['model' => Project::class, 'column' => 'billing_status_id'],
            ['model' => Person::class, 'column' => 'worker_status_id'],
            ['model' => ProjectAssignment::class, 'column' => 'assignment_status_id'],
        ],
        'fields' => [
            'domain' => ['label' => 'Dominio', 'type' => 'select', 'options' => ['client' => 'Clientes', 'project' => 'Proyectos', 'billing' => 'Facturación', 'worker' => 'Personal', 'assignment' => 'Asignaciones']],
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'name' => ['label' => 'Nombre', 'type' => 'text'],
            'description' => ['label' => 'Descripcion', 'type' => 'textarea'],
            'active' => ['label' => 'Activo', 'type' => 'checkbox'],
            'sort_order' => ['label' => 'Orden', 'type' => 'number'],
        ],
        'rules' => array_merge($catalogBaseRules, ['domain' => ['required', 'string', 'in:client,project,billing,worker,assignment']]),
    ],
    'client-types' => [
        'title' => 'Tipos de cliente',
        'section' => 'Administración',
        'breadcrumb_group' => 'Mantenedores',
        'model' => ClientType::class,
        'display' => 'name',
        'catalog' => true,
        'admin_only' => true,
        'usage' => [['model' => Client::class, 'column' => 'client_type_id']],
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'name' => ['label' => 'Nombre', 'type' => 'text'],
            'description' => ['label' => 'Descripcion', 'type' => 'textarea'],
            'active' => ['label' => 'Activo', 'type' => 'checkbox'],
            'sort_order' => ['label' => 'Orden', 'type' => 'number'],
        ],
        'rules' => $catalogBaseRules,
    ],
    'project-types' => [
        'title' => 'Tipos de proyecto',
        'section' => 'Administración',
        'breadcrumb_group' => 'Mantenedores',
        'model' => ProjectType::class,
        'display' => 'name',
        'catalog' => true,
        'admin_only' => true,
        'usage' => [['model' => Project::class, 'column' => 'project_type_id']],
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'name' => ['label' => 'Nombre', 'type' => 'text'],
            'description' => ['label' => 'Descripcion', 'type' => 'textarea'],
            'active' => ['label' => 'Activo', 'type' => 'checkbox'],
            'sort_order' => ['label' => 'Orden', 'type' => 'number'],
        ],
        'rules' => $catalogBaseRules,
    ],
    'payment-terms' => [
        'title' => 'Condiciones/Formas de pago',
        'section' => 'Administración',
        'breadcrumb_group' => 'Mantenedores',
        'model' => PaymentTerm::class,
        'display' => 'name',
        'catalog' => true,
        'admin_only' => true,
        'usage' => [
            ['model' => Client::class, 'column' => 'payment_term_id'],
            ['model' => Project::class, 'column' => 'payment_term_id'],
        ],
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'name' => ['label' => 'Nombre', 'type' => 'text'],
            'days' => ['label' => 'Días', 'type' => 'number'],
            'payment_method_id' => ['label' => 'Medio pago base', 'type' => 'relation', 'model' => PaymentMethod::class, 'display' => 'name'],
            'description' => ['label' => 'Descripcion', 'type' => 'textarea'],
            'active' => ['label' => 'Activo', 'type' => 'checkbox'],
            'sort_order' => ['label' => 'Orden', 'type' => 'number'],
        ],
        'rules' => array_merge($catalogBaseRules, [
            'days' => ['nullable', 'integer', 'min:0'],
            'payment_method_id' => ['nullable', 'integer'],
        ]),
    ],
    'currencies' => [
        'title' => 'Monedas',
        'section' => 'Administración',
        'breadcrumb_group' => 'Mantenedores',
        'model' => Currency::class,
        'display' => 'name',
        'catalog' => true,
        'admin_only' => true,
        'usage' => [['model' => CashAccount::class, 'column' => 'currency_id']],
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'name' => ['label' => 'Nombre', 'type' => 'text'],
            'symbol' => ['label' => 'Símbolo', 'type' => 'text'],
            'minor_units' => ['label' => 'Decimales', 'type' => 'number'],
            'is_base_currency' => ['label' => 'Moneda base', 'type' => 'checkbox'],
            'description' => ['label' => 'Descripcion', 'type' => 'textarea'],
            'active' => ['label' => 'Activo', 'type' => 'checkbox'],
            'sort_order' => ['label' => 'Orden', 'type' => 'number'],
        ],
        'rules' => array_merge($catalogBaseRules, [
            'symbol' => ['required', 'string', 'max:12'],
            'minor_units' => ['required', 'integer', 'min:0', 'max:6'],
            'is_base_currency' => ['nullable', 'boolean'],
        ]),
    ],
    'company-settings' => [
        'title' => 'Parámetros empresa',
        'section' => 'Administración',
        'breadcrumb_group' => 'Parámetros y valores',
        'model' => CompanySetting::class,
        'display' => 'setting_key',
        'catalog' => true,
        'admin_only' => true,
        'active_column' => 'active',
        'fields' => [
            'setting_key' => ['label' => 'Código', 'type' => 'text'],
            'setting_value' => ['label' => 'Valor', 'type' => 'text'],
            'setting_type' => ['label' => 'Tipo', 'type' => 'select', 'options' => ['string' => 'Texto', 'integer' => 'Entero', 'decimal' => 'Decimal', 'boolean' => 'Booleano', 'date' => 'Fecha']],
            'is_public' => ['label' => 'Público', 'type' => 'checkbox'],
            'active' => ['label' => 'Activo', 'type' => 'checkbox'],
        ],
        'rules' => [
            'setting_key' => ['required', 'string', 'max:100'],
            'setting_value' => ['nullable', 'string'],
            'setting_type' => ['required', 'in:string,integer,decimal,boolean,date'],
            'is_public' => ['nullable', 'boolean'],
            'active' => ['nullable', 'boolean'],
        ],
    ],
    'legal-parameters' => [
        'title' => 'Parámetros legales',
        'section' => 'Administración',
        'breadcrumb_group' => 'Parámetros y valores',
        'model' => LegalParameter::class,
        'display' => 'parameter_name',
        'catalog' => true,
        'admin_only' => true,
        'active_column' => 'active',
        'fields' => [
            'parameter_code' => ['label' => 'Código', 'type' => 'text'],
            'parameter_name' => ['label' => 'Nombre', 'type' => 'text'],
            'category' => ['label' => 'Categoría', 'type' => 'text'],
            'value' => ['label' => 'Valor', 'type' => 'decimal'],
            'unit' => ['label' => 'Unidad', 'type' => 'select', 'options' => ['PERCENT' => 'PERCENT', '%' => '%', 'CLP' => 'CLP', 'UF' => 'UF', 'UTM' => 'UTM', 'NUMBER' => 'NUMBER', 'DAYS' => 'DAYS', 'HOURS' => 'HOURS', 'BOOLEAN' => 'BOOLEAN']],
            'valid_from' => ['label' => 'Desde', 'type' => 'date'],
            'valid_to' => ['label' => 'Hasta', 'type' => 'date'],
            'source_name' => ['label' => 'Fuente', 'type' => 'text'],
            'source_url' => ['label' => 'URL fuente', 'type' => 'text'],
            'notes' => ['label' => 'Observación', 'type' => 'textarea'],
            'active' => ['label' => 'Activo', 'type' => 'checkbox'],
        ],
        'rules' => [
            'parameter_code' => ['required', 'string', 'max:80'],
            'parameter_name' => ['required', 'string', 'max:255'],
            'category' => ['nullable', 'string', 'max:80'],
            'value' => ['required', 'numeric'],
            'unit' => ['required', 'string', 'max:20'],
            'valid_from' => ['required', 'date'],
            'valid_to' => ['nullable', 'date', 'after_or_equal:valid_from'],
            'source_name' => ['nullable', 'string', 'max:255'],
            'source_url' => ['nullable', 'string', 'max:255'],
            'notes' => ['nullable', 'string'],
            'active' => ['nullable', 'boolean'],
        ],
    ],
    'uf-values' => [
        'title' => 'UF',
        'section' => 'Administración',
        'breadcrumb_group' => 'Parámetros y valores',
        'model' => UfValue::class,
        'display' => 'value_date',
        'catalog' => true,
        'admin_only' => true,
        'active_column' => 'active',
        'fields' => [
            'value_date' => ['label' => 'Fecha', 'type' => 'date'],
            'value' => ['label' => 'Valor UF', 'type' => 'decimal', 'presentation' => 'uf'],
            'source_name' => ['label' => 'Fuente', 'type' => 'text'],
            'source_url' => ['label' => 'URL fuente', 'type' => 'text'],
            'notes' => ['label' => 'Observación', 'type' => 'textarea'],
            'active' => ['label' => 'Activo', 'type' => 'checkbox'],
        ],
        'rules' => [
            'value_date' => ['required', 'date'],
            'value' => ['required', 'numeric', 'min:0'],
            'source_name' => ['nullable', 'string', 'max:255'],
            'source_url' => ['nullable', 'string', 'max:255'],
            'notes' => ['nullable', 'string'],
            'active' => ['nullable', 'boolean'],
        ],
    ],
    'utm-values' => [
        'title' => 'UTM',
        'section' => 'Administración',
        'breadcrumb_group' => 'Parámetros y valores',
        'model' => UtmValue::class,
        'display' => 'period_year',
        'catalog' => true,
        'admin_only' => true,
        'active_column' => 'active',
        'fields' => [
            'period_year' => ['label' => 'Año', 'type' => 'number'],
            'period_month' => ['label' => 'Mes', 'type' => 'number'],
            'value' => ['label' => 'Valor UTM', 'type' => 'decimal'],
            'source_name' => ['label' => 'Fuente', 'type' => 'text'],
            'source_url' => ['label' => 'URL fuente', 'type' => 'text'],
            'notes' => ['label' => 'Observación', 'type' => 'textarea'],
            'active' => ['label' => 'Activo', 'type' => 'checkbox'],
        ],
        'rules' => [
            'period_year' => ['required', 'integer', 'min:2000', 'max:2100'],
            'period_month' => ['required', 'integer', 'min:1', 'max:12'],
            'value' => ['required', 'numeric', 'min:0'],
            'source_name' => ['nullable', 'string', 'max:255'],
            'source_url' => ['nullable', 'string', 'max:255'],
            'notes' => ['nullable', 'string'],
            'active' => ['nullable', 'boolean'],
        ],
    ],
    'exchange-rates' => [
        'title' => 'Tipos de cambio',
        'section' => 'Administración',
        'breadcrumb_group' => 'Parámetros y valores',
        'model' => ExchangeRate::class,
        'display' => 'rate_date',
        'catalog' => true,
        'admin_only' => true,
        'active_column' => 'active',
        'fields' => [
            'currency_id' => ['label' => 'Moneda', 'type' => 'relation', 'model' => Currency::class, 'display' => 'name'],
            'rate_date' => ['label' => 'Fecha', 'type' => 'date'],
            'value_clp' => ['label' => 'Valor en CLP', 'type' => 'decimal', 'presentation' => 'exchange_rate'],
            'source_name' => ['label' => 'Fuente', 'type' => 'text'],
            'source_url' => ['label' => 'URL fuente', 'type' => 'text'],
            'notes' => ['label' => 'Observación', 'type' => 'textarea'],
            'active' => ['label' => 'Activo', 'type' => 'checkbox'],
        ],
        'rules' => [
            'currency_id' => ['required', 'integer'],
            'rate_date' => ['required', 'date'],
            'value_clp' => ['required', 'numeric', 'min:0'],
            'source_name' => ['nullable', 'string', 'max:255'],
            'source_url' => ['nullable', 'string', 'max:255'],
            'notes' => ['nullable', 'string'],
            'active' => ['nullable', 'boolean'],
        ],
    ],
    'afp-rates' => [
        'title' => 'AFP y tasas',
        'section' => 'Administración',
        'breadcrumb_group' => 'Parámetros y valores',
        'model' => AfpRate::class,
        'display' => 'valid_from',
        'catalog' => true,
        'admin_only' => true,
        'active_column' => 'active',
        'fields' => [
            'afp_id' => ['label' => 'AFP', 'type' => 'relation', 'model' => Afp::class, 'display' => 'name', 'global' => true],
            'valid_from' => ['label' => 'Desde', 'type' => 'date'],
            'valid_to' => ['label' => 'Hasta', 'type' => 'date'],
            'employee_commission_rate' => ['label' => 'Comisión trabajador', 'type' => 'decimal', 'presentation' => 'percent'],
            'employer_commission_rate' => ['label' => 'Comisión empleador', 'type' => 'decimal', 'presentation' => 'percent'],
            'insurance_rate' => ['label' => 'Seguro', 'type' => 'decimal', 'presentation' => 'percent'],
            'source' => ['label' => 'Fuente', 'type' => 'text'],
            'source_url' => ['label' => 'URL fuente', 'type' => 'text'],
            'active' => ['label' => 'Activo', 'type' => 'checkbox'],
        ],
        'rules' => [
            'afp_id' => ['required', 'integer'],
            'valid_from' => ['required', 'date'],
            'valid_to' => ['nullable', 'date', 'after_or_equal:valid_from'],
            'employee_commission_rate' => ['required', 'numeric', 'min:0'],
            'employer_commission_rate' => ['nullable', 'numeric', 'min:0'],
            'insurance_rate' => ['nullable', 'numeric', 'min:0'],
            'source' => ['nullable', 'string', 'max:255'],
            'source_url' => ['nullable', 'string', 'max:255'],
            'active' => ['nullable', 'boolean'],
        ],
    ],
    'income-tax-brackets' => [
        'title' => 'Tabla IUSC',
        'section' => 'Administración',
        'breadcrumb_group' => 'Parámetros y valores',
        'model' => IncomeTaxBracket::class,
        'display' => 'period_year',
        'catalog' => true,
        'admin_only' => true,
        'active_column' => 'active',
        'fields' => [
            'period_year' => ['label' => 'Año', 'type' => 'number'],
            'period_month' => ['label' => 'Mes', 'type' => 'number'],
            'period_type' => ['label' => 'Tipo período', 'type' => 'text'],
            'from_amount' => ['label' => 'Desde', 'type' => 'money'],
            'to_amount' => ['label' => 'Hasta', 'type' => 'money'],
            'factor' => ['label' => 'Factor', 'type' => 'decimal', 'presentation' => 'percent'],
            'rebate_amount' => ['label' => 'Rebaja', 'type' => 'money'],
            'effective_max_rate' => ['label' => 'Tasa máxima efectiva', 'type' => 'decimal', 'presentation' => 'percent'],
            'source_url' => ['label' => 'URL fuente', 'type' => 'text'],
            'active' => ['label' => 'Activo', 'type' => 'checkbox'],
        ],
        'rules' => [
            'period_year' => ['required', 'integer', 'min:2000', 'max:2100'],
            'period_month' => ['required', 'integer', 'min:1', 'max:12'],
            'period_type' => ['required', 'string', 'max:20'],
            'from_amount' => ['required', 'numeric', 'min:0'],
            'to_amount' => ['nullable', 'numeric', 'min:0'],
            'factor' => ['required', 'numeric', 'min:0'],
            'rebate_amount' => ['required', 'numeric', 'min:0'],
            'effective_max_rate' => ['nullable', 'numeric', 'min:0'],
            'source_url' => ['nullable', 'string', 'max:255'],
            'active' => ['nullable', 'boolean'],
        ],
    ],
    'activities' => [
        'title' => 'Actividades',
        'section' => 'Administración',
        'breadcrumb_group' => 'Mantenedores',
        'model' => Activity::class,
        'display' => 'name',
        'catalog' => true,
        'admin_only' => true,
        'usage' => [['model' => TimeEntry::class, 'column' => 'activity_id']],
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'name' => ['label' => 'Nombre', 'type' => 'text'],
            'description' => ['label' => 'Descripcion', 'type' => 'textarea'],
            'active' => ['label' => 'Activo', 'type' => 'checkbox'],
            'sort_order' => ['label' => 'Orden', 'type' => 'number'],
        ],
        'rules' => $catalogBaseRules,
    ],
    'approval-statuses' => [
        'title' => 'Estados de aprobación',
        'section' => 'Administración',
        'breadcrumb_group' => 'Mantenedores',
        'model' => ApprovalStatus::class,
        'display' => 'name',
        'catalog' => true,
        'admin_only' => true,
        'usage' => [['model' => TimeEntry::class, 'column' => 'approval_status_id']],
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'name' => ['label' => 'Nombre', 'type' => 'text'],
            'description' => ['label' => 'Descripcion', 'type' => 'textarea'],
            'active' => ['label' => 'Activo', 'type' => 'checkbox'],
            'sort_order' => ['label' => 'Orden', 'type' => 'number'],
        ],
        'rules' => $catalogBaseRules,
    ],
    'expense-types' => [
        'title' => 'Tipos de gasto',
        'section' => 'Administración',
        'breadcrumb_group' => 'Mantenedores',
        'model' => ExpenseType::class,
        'display' => 'name',
        'catalog' => true,
        'admin_only' => true,
        'usage' => [['model' => ExpenseDocument::class, 'column' => 'expense_type_id']],
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'name' => ['label' => 'Nombre', 'type' => 'text'],
            'description' => ['label' => 'Descripcion', 'type' => 'textarea'],
            'active' => ['label' => 'Activo', 'type' => 'checkbox'],
            'sort_order' => ['label' => 'Orden', 'type' => 'number'],
        ],
        'rules' => $catalogBaseRules,
    ],
    'cash-movement-types' => [
        'title' => 'Tipos de movimiento',
        'section' => 'Administración',
        'breadcrumb_group' => 'Mantenedores',
        'model' => CashMovementType::class,
        'display' => 'name',
        'catalog' => true,
        'admin_only' => true,
        'usage' => [['model' => CashMovement::class, 'column' => 'movement_type_id']],
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'name' => ['label' => 'Nombre', 'type' => 'text'],
            'description' => ['label' => 'Descripcion', 'type' => 'textarea'],
            'active' => ['label' => 'Activo', 'type' => 'checkbox'],
            'sort_order' => ['label' => 'Orden', 'type' => 'number'],
        ],
        'rules' => $catalogBaseRules,
    ],
    'bank-account-types' => [
        'title' => 'Tipos de cuenta bancaria',
        'section' => 'Administración',
        'breadcrumb_group' => 'Mantenedores',
        'model' => BankAccountType::class,
        'display' => 'name',
        'catalog' => true,
        'admin_only' => true,
        'usage' => [['model' => CashAccount::class, 'column' => 'bank_account_type_id']],
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'name' => ['label' => 'Nombre', 'type' => 'text'],
            'description' => ['label' => 'Descripcion', 'type' => 'textarea'],
            'active' => ['label' => 'Activo', 'type' => 'checkbox'],
            'sort_order' => ['label' => 'Orden', 'type' => 'number'],
        ],
        'rules' => $catalogBaseRules,
    ],
    'afps' => [
        'title' => 'AFP',
        'section' => 'Administración',
        'breadcrumb_group' => 'Mantenedores',
        'model' => Afp::class,
        'display' => 'name',
        'catalog' => true,
        'admin_only' => true,
        'active_column' => 'is_active',
        'usage' => [['model' => Person::class, 'column' => 'afp_id']],
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'name' => ['label' => 'Nombre', 'type' => 'text'],
            'is_active' => ['label' => 'Activo', 'type' => 'checkbox'],
        ],
        'rules' => [
            'code' => ['required', 'string', 'max:40'],
            'name' => ['required', 'string', 'max:255'],
            'is_active' => ['nullable', 'boolean'],
        ],
    ],
    'health-systems' => [
        'title' => 'Sistemas de salud',
        'section' => 'Administración',
        'breadcrumb_group' => 'Mantenedores',
        'model' => HealthSystem::class,
        'display' => 'name',
        'catalog' => true,
        'admin_only' => true,
        'usage' => [['model' => Person::class, 'column' => 'health_system_id']],
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'name' => ['label' => 'Nombre', 'type' => 'text'],
            'description' => ['label' => 'Descripcion', 'type' => 'textarea'],
            'active' => ['label' => 'Activo', 'type' => 'checkbox'],
            'sort_order' => ['label' => 'Orden', 'type' => 'number'],
        ],
        'rules' => $catalogBaseRules,
    ],
    'tax-regimes' => [
        'title' => 'Regímenes tributarios',
        'section' => 'Administración',
        'breadcrumb_group' => 'Mantenedores',
        'model' => TaxRegime::class,
        'display' => 'name',
        'catalog' => true,
        'admin_only' => true,
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'name' => ['label' => 'Nombre', 'type' => 'text'],
            'description' => ['label' => 'Descripcion', 'type' => 'textarea'],
            'active' => ['label' => 'Activo', 'type' => 'checkbox'],
            'sort_order' => ['label' => 'Orden', 'type' => 'number'],
        ],
        'rules' => $catalogBaseRules,
    ],
    'legal-organizations' => [
        'title' => 'Organismos',
        'section' => 'Administración',
        'breadcrumb_group' => 'Mantenedores',
        'model' => LegalOrganization::class,
        'display' => 'name',
        'catalog' => true,
        'admin_only' => true,
        'usage' => [['model' => LegalObligation::class, 'column' => 'organization_id']],
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'name' => ['label' => 'Nombre', 'type' => 'text'],
            'description' => ['label' => 'Descripcion', 'type' => 'textarea'],
            'active' => ['label' => 'Activo', 'type' => 'checkbox'],
            'sort_order' => ['label' => 'Orden', 'type' => 'number'],
        ],
        'rules' => $catalogBaseRules,
    ],
    'occupational-insurance-entities' => [
        'title' => 'Mutualidades',
        'section' => 'Administración',
        'breadcrumb_group' => 'Mantenedores',
        'model' => OccupationalInsuranceEntity::class,
        'display' => 'name',
        'catalog' => true,
        'admin_only' => true,
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'name' => ['label' => 'Nombre', 'type' => 'text'],
            'description' => ['label' => 'Descripcion', 'type' => 'textarea'],
            'active' => ['label' => 'Activo', 'type' => 'checkbox'],
            'sort_order' => ['label' => 'Orden', 'type' => 'number'],
        ],
        'rules' => $catalogBaseRules,
    ],
];
