<?php

use App\Models\Activity;
use App\Models\Afp;
use App\Models\ApprovalStatus;
use App\Models\Bank;
use App\Models\BankAccountType;
use App\Models\Budget;
use App\Models\CashAccount;
use App\Models\CashMovement;
use App\Models\CashMovementType;
use App\Models\Client;
use App\Models\ClientType;
use App\Models\ContractType;
use App\Models\CostCenter;
use App\Models\Currency;
use App\Models\DocumentType;
use App\Models\EmploymentMode;
use App\Models\ExpenseCategory;
use App\Models\ExpenseDocument;
use App\Models\ExpenseSubcategory;
use App\Models\ExpenseType;
use App\Models\HealthSystem;
use App\Models\LegalOrganization;
use App\Models\LegalObligation;
use App\Models\ObligationType;
use App\Models\OccupationalInsuranceEntity;
use App\Models\PaymentMethod;
use App\Models\PaymentTerm;
use App\Models\PayrollRecord;
use App\Models\Person;
use App\Models\Position;
use App\Models\Project;
use App\Models\ProjectAssignment;
use App\Models\ProjectManager;
use App\Models\ProjectType;
use App\Models\RecordStatus;
use App\Models\SalesDocument;
use App\Models\Scenario;
use App\Models\TaxRegime;
use App\Models\TimeEntry;

$catalogBaseRules = [
    'code' => ['required', 'string', 'max:80'],
    'name' => ['required', 'string', 'max:255'],
    'description' => ['nullable', 'string'],
    'active' => ['nullable', 'boolean'],
    'sort_order' => ['nullable', 'integer', 'min:0'],
];

return [
    'clients' => [
        'title' => 'Clientes',
        'section' => 'Operación',
        'model' => Client::class,
        'display' => 'legal_name',
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'legal_name' => ['label' => 'Razon social', 'type' => 'text'],
            'tax_id' => ['label' => 'RUT', 'type' => 'text'],
            'client_type_id' => ['label' => 'Tipo cliente', 'type' => 'relation', 'model' => ClientType::class, 'display' => 'name'],
            'contact_name' => ['label' => 'Contacto', 'type' => 'text'],
            'contact_email' => ['label' => 'Correo', 'type' => 'email'],
            'payment_term_id' => ['label' => 'Condición de pago', 'type' => 'relation', 'model' => PaymentTerm::class, 'display' => 'name'],
            'client_status_id' => ['label' => 'Estado', 'type' => 'relation', 'model' => RecordStatus::class, 'display' => 'name', 'where' => ['domain' => 'client']],
            'notes' => ['label' => 'Notas', 'type' => 'textarea'],
        ],
        'rules' => [
            'code' => ['required', 'string', 'max:40'],
            'legal_name' => ['required', 'string', 'max:255'],
            'tax_id' => ['nullable', 'string', 'max:30'],
            'client_type_id' => ['nullable', 'integer'],
            'contact_name' => ['nullable', 'string', 'max:255'],
            'contact_email' => ['nullable', 'email', 'max:255'],
            'payment_term_id' => ['nullable', 'integer'],
            'client_status_id' => ['required', 'integer'],
            'notes' => ['nullable', 'string'],
        ],
    ],
    'projects' => [
        'title' => 'Proyectos',
        'section' => 'Operación',
        'model' => Project::class,
        'display' => 'name',
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'client_id' => ['label' => 'Cliente', 'type' => 'relation', 'model' => Client::class, 'display' => 'legal_name'],
            'name' => ['label' => 'Proyecto/Servicio', 'type' => 'text'],
            'project_type_id' => ['label' => 'Tipo proyecto', 'type' => 'relation', 'model' => ProjectType::class, 'display' => 'name'],
            'manager_id' => ['label' => 'Responsable', 'type' => 'relation', 'model' => ProjectManager::class, 'display' => 'name'],
            'start_date' => ['label' => 'Fecha inicio', 'type' => 'date'],
            'end_date' => ['label' => 'Fecha termino', 'type' => 'date'],
            'contract_type_id' => ['label' => 'Tipo contrato', 'type' => 'relation', 'model' => ContractType::class, 'display' => 'name', 'where' => ['domain' => 'commercial']],
            'payment_term_id' => ['label' => 'Forma/condición pago', 'type' => 'relation', 'model' => PaymentTerm::class, 'display' => 'name'],
            'sale_net' => ['label' => 'Venta neta', 'type' => 'money'],
            'vat_rate' => ['label' => 'Tasa IVA', 'type' => 'decimal'],
            'sale_total' => ['label' => 'Venta total', 'type' => 'money'],
            'project_status_id' => ['label' => 'Estado proyecto', 'type' => 'relation', 'model' => RecordStatus::class, 'display' => 'name', 'where' => ['domain' => 'project']],
            'billing_status_id' => ['label' => 'Estado facturacion', 'type' => 'relation', 'model' => RecordStatus::class, 'display' => 'name', 'where' => ['domain' => 'billing']],
        ],
        'rules' => [
            'code' => ['required', 'string', 'max:40'],
            'client_id' => ['required', 'integer', 'exists:clients,id'],
            'name' => ['required', 'string', 'max:255'],
            'project_type_id' => ['nullable', 'integer'],
            'manager_id' => ['nullable', 'integer'],
            'start_date' => ['nullable', 'date'],
            'end_date' => ['nullable', 'date', 'after_or_equal:start_date'],
            'contract_type_id' => ['nullable', 'integer'],
            'payment_term_id' => ['nullable', 'integer'],
            'sale_net' => ['nullable', 'numeric', 'min:0'],
            'vat_rate' => ['nullable', 'numeric', 'min:0'],
            'sale_total' => ['nullable', 'numeric', 'min:0'],
            'project_status_id' => ['required', 'integer'],
            'billing_status_id' => ['required', 'integer'],
        ],
    ],
    'people' => [
        'title' => 'Personal',
        'section' => 'Operación',
        'model' => Person::class,
        'display' => 'name',
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'name' => ['label' => 'Nombre', 'type' => 'text'],
            'identifier' => ['label' => 'Identificador', 'type' => 'text'],
            'position_id' => ['label' => 'Cargo', 'type' => 'relation', 'model' => Position::class, 'display' => 'name'],
            'employment_mode_id' => ['label' => 'Modalidad', 'type' => 'relation', 'model' => EmploymentMode::class, 'display' => 'name'],
            'employment_contract_type_id' => ['label' => 'Tipo contrato', 'type' => 'relation', 'model' => ContractType::class, 'display' => 'name', 'where' => ['domain' => 'employment']],
            'afp_id' => ['label' => 'AFP', 'type' => 'relation', 'model' => Afp::class, 'display' => 'name', 'active_column' => 'is_active'],
            'health_system_id' => ['label' => 'Sistema de salud', 'type' => 'relation', 'model' => HealthSystem::class, 'display' => 'name', 'relation_name' => 'healthSystemCatalog'],
            'monthly_value' => ['label' => 'Valor mensual', 'type' => 'money'],
            'hourly_value' => ['label' => 'Valor hora', 'type' => 'money'],
            'monthly_hours' => ['label' => 'Horas mensuales', 'type' => 'number'],
            'worker_status_id' => ['label' => 'Estado', 'type' => 'relation', 'model' => RecordStatus::class, 'display' => 'name', 'where' => ['domain' => 'worker']],
            'start_date' => ['label' => 'Fecha inicio', 'type' => 'date'],
            'end_date' => ['label' => 'Fecha termino', 'type' => 'date'],
        ],
        'rules' => [
            'code' => ['required', 'string', 'max:40'],
            'name' => ['required', 'string', 'max:255'],
            'identifier' => ['nullable', 'string', 'max:40'],
            'position_id' => ['nullable', 'integer'],
            'employment_mode_id' => ['required', 'integer'],
            'employment_contract_type_id' => ['nullable', 'integer'],
            'afp_id' => ['nullable', 'integer'],
            'health_system_id' => ['nullable', 'integer'],
            'monthly_value' => ['nullable', 'numeric', 'min:0'],
            'hourly_value' => ['nullable', 'numeric', 'min:0'],
            'monthly_hours' => ['nullable', 'integer', 'min:0'],
            'worker_status_id' => ['required', 'integer'],
            'start_date' => ['nullable', 'date'],
            'end_date' => ['nullable', 'date', 'after_or_equal:start_date'],
        ],
    ],
    'assignments' => [
        'title' => 'Asignaciones',
        'section' => 'Operación',
        'model' => ProjectAssignment::class,
        'display' => 'code',
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'person_id' => ['label' => 'Persona', 'type' => 'relation', 'model' => Person::class, 'display' => 'name'],
            'client_id' => ['label' => 'Cliente', 'type' => 'relation', 'model' => Client::class, 'display' => 'legal_name'],
            'project_id' => ['label' => 'Proyecto', 'type' => 'relation', 'model' => Project::class, 'display' => 'name'],
            'hourly_value' => ['label' => 'Valor hora', 'type' => 'money'],
            'project_value' => ['label' => 'Valor proyecto', 'type' => 'money'],
            'monthly_hours' => ['label' => 'Horas mensuales', 'type' => 'number'],
            'cost_center_id' => ['label' => 'Centro costo', 'type' => 'relation', 'model' => CostCenter::class, 'display' => 'name'],
            'start_date' => ['label' => 'Fecha inicio', 'type' => 'date'],
            'end_date' => ['label' => 'Fecha termino', 'type' => 'date'],
            'assignment_status_id' => ['label' => 'Estado', 'type' => 'relation', 'model' => RecordStatus::class, 'display' => 'name', 'where' => ['domain' => 'assignment']],
        ],
        'rules' => [
            'code' => ['required', 'string', 'max:40'],
            'person_id' => ['required', 'integer', 'exists:people,id'],
            'client_id' => ['required', 'integer', 'exists:clients,id'],
            'project_id' => ['required', 'integer', 'exists:projects,id'],
            'hourly_value' => ['nullable', 'numeric', 'min:0'],
            'project_value' => ['nullable', 'numeric', 'min:0'],
            'monthly_hours' => ['nullable', 'integer', 'min:0'],
            'cost_center_id' => ['nullable', 'integer'],
            'start_date' => ['nullable', 'date'],
            'end_date' => ['nullable', 'date', 'after_or_equal:start_date'],
            'assignment_status_id' => ['required', 'integer'],
        ],
    ],
    'time-entries' => [
        'title' => 'Horas',
        'section' => 'Operación',
        'model' => TimeEntry::class,
        'display' => 'activity',
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'entry_date' => ['label' => 'Fecha', 'type' => 'date'],
            'person_id' => ['label' => 'Persona', 'type' => 'relation', 'model' => Person::class, 'display' => 'name'],
            'client_id' => ['label' => 'Cliente', 'type' => 'relation', 'model' => Client::class, 'display' => 'legal_name'],
            'project_id' => ['label' => 'Proyecto', 'type' => 'relation', 'model' => Project::class, 'display' => 'name'],
            'activity_id' => ['label' => 'Actividad', 'type' => 'relation', 'model' => Activity::class, 'display' => 'name', 'relation_name' => 'activityCatalog'],
            'hours_worked' => ['label' => 'Horas trabajadas', 'type' => 'decimal'],
            'hours_approved' => ['label' => 'Horas aprobadas', 'type' => 'decimal'],
            'hourly_value' => ['label' => 'Valor hora', 'type' => 'money'],
            'cost_center_id' => ['label' => 'Centro costo', 'type' => 'relation', 'model' => CostCenter::class, 'display' => 'name'],
            'approval_status_id' => ['label' => 'Aprobacion', 'type' => 'relation', 'model' => ApprovalStatus::class, 'display' => 'name'],
            'payment_status' => ['label' => 'Pago', 'type' => 'select', 'options' => ['pending' => 'Pendiente', 'paid' => 'Pagado']],
        ],
        'rules' => [
            'code' => ['required', 'string', 'max:40'],
            'entry_date' => ['required', 'date'],
            'person_id' => ['required', 'integer', 'exists:people,id'],
            'client_id' => ['required', 'integer', 'exists:clients,id'],
            'project_id' => ['required', 'integer', 'exists:projects,id'],
            'activity_id' => ['required', 'integer'],
            'hours_worked' => ['required', 'numeric', 'min:0'],
            'hours_approved' => ['required', 'numeric', 'min:0'],
            'hourly_value' => ['required', 'numeric', 'min:0'],
            'cost_center_id' => ['nullable', 'integer'],
            'approval_status_id' => ['required', 'integer'],
            'payment_status' => ['required', 'string', 'max:20'],
        ],
    ],
    'sales-documents' => [
        'title' => 'Facturas/Ingresos',
        'section' => 'Ventas',
        'model' => SalesDocument::class,
        'display' => 'code',
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'client_id' => ['label' => 'Cliente', 'type' => 'relation', 'model' => Client::class, 'display' => 'legal_name'],
            'project_id' => ['label' => 'Proyecto', 'type' => 'relation', 'model' => Project::class, 'display' => 'name'],
            'document_type_id' => ['label' => 'Tipo documento', 'type' => 'relation', 'model' => DocumentType::class, 'display' => 'name', 'where' => ['domain' => 'sales']],
            'document_number' => ['label' => 'Numero', 'type' => 'text'],
            'issue_date' => ['label' => 'Fecha emision', 'type' => 'date'],
            'due_date' => ['label' => 'Fecha vencimiento', 'type' => 'date'],
            'projected_collection_date' => ['label' => 'Cobro proyectado', 'type' => 'date'],
            'payment_probability' => ['label' => 'Probabilidad', 'type' => 'decimal'],
            'net_amount' => ['label' => 'Neto', 'type' => 'money'],
            'gross_amount' => ['label' => 'Total', 'type' => 'money'],
            'status' => ['label' => 'Estado', 'type' => 'text', 'readonly' => true],
            'is_voided' => ['label' => 'Anulado', 'type' => 'checkbox'],
        ],
        'rules' => [
            'code' => ['required', 'string', 'max:40'],
            'client_id' => ['required', 'integer', 'exists:clients,id'],
            'project_id' => ['nullable', 'integer', 'exists:projects,id'],
            'document_type_id' => ['required', 'integer'],
            'document_number' => ['nullable', 'string', 'max:60'],
            'issue_date' => ['required', 'date'],
            'due_date' => ['nullable', 'date'],
            'projected_collection_date' => ['nullable', 'date'],
            'payment_probability' => ['nullable', 'numeric', 'min:0', 'max:1'],
            'net_amount' => ['required', 'numeric', 'min:0'],
            'gross_amount' => ['nullable', 'numeric', 'min:0'],
            'is_voided' => ['nullable', 'boolean'],
        ],
    ],
    'expense-documents' => [
        'title' => 'Gastos/Egresos',
        'section' => 'Gastos',
        'model' => ExpenseDocument::class,
        'display' => 'code',
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'vendor_name' => ['label' => 'Proveedor', 'type' => 'text'],
            'client_id' => ['label' => 'Cliente', 'type' => 'relation', 'model' => Client::class, 'display' => 'legal_name'],
            'project_id' => ['label' => 'Proyecto', 'type' => 'relation', 'model' => Project::class, 'display' => 'name'],
            'expense_category_id' => ['label' => 'Categoria', 'type' => 'relation', 'model' => ExpenseCategory::class, 'display' => 'name'],
            'expense_subcategory_id' => ['label' => 'Subcategoria', 'type' => 'relation', 'model' => ExpenseSubcategory::class, 'display' => 'name', 'depends_on' => 'expense_category_id', 'option_parent_key' => 'expense_category_id'],
            'expense_type_id' => ['label' => 'Tipo gasto', 'type' => 'relation', 'model' => ExpenseType::class, 'display' => 'name', 'relation_name' => 'expenseType'],
            'document_type_id' => ['label' => 'Tipo documento', 'type' => 'relation', 'model' => DocumentType::class, 'display' => 'name', 'where' => ['domain' => 'expense']],
            'issue_date' => ['label' => 'Fecha documento', 'type' => 'date'],
            'due_date' => ['label' => 'Vencimiento', 'type' => 'date'],
            'net_amount' => ['label' => 'Neto', 'type' => 'money'],
            'gross_amount' => ['label' => 'Total', 'type' => 'money'],
            'deductible_vat' => ['label' => 'IVA recuperable', 'type' => 'checkbox'],
            'payment_status' => ['label' => 'Estado', 'type' => 'text', 'readonly' => true],
        ],
        'rules' => [
            'code' => ['required', 'string', 'max:40'],
            'vendor_name' => ['nullable', 'string', 'max:255'],
            'client_id' => ['nullable', 'integer', 'exists:clients,id'],
            'project_id' => ['nullable', 'integer', 'exists:projects,id'],
            'expense_category_id' => ['nullable', 'integer'],
            'expense_subcategory_id' => ['nullable', 'integer'],
            'expense_type_id' => ['nullable', 'integer'],
            'document_type_id' => ['nullable', 'integer'],
            'issue_date' => ['required', 'date'],
            'due_date' => ['nullable', 'date'],
            'net_amount' => ['required', 'numeric', 'min:0'],
            'gross_amount' => ['nullable', 'numeric', 'min:0'],
            'deductible_vat' => ['nullable', 'boolean'],
        ],
    ],
    'cash-accounts' => [
        'title' => 'Cuentas de caja/banco',
        'section' => 'Tesorería',
        'model' => CashAccount::class,
        'display' => 'name',
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'name' => ['label' => 'Nombre', 'type' => 'text'],
            'bank_id' => ['label' => 'Banco', 'type' => 'relation', 'model' => Bank::class, 'display' => 'name'],
            'bank_account_type_id' => ['label' => 'Tipo cuenta', 'type' => 'relation', 'model' => BankAccountType::class, 'display' => 'name'],
            'currency_id' => ['label' => 'Moneda', 'type' => 'relation', 'model' => Currency::class, 'display' => 'name', 'relation_name' => 'currencyCatalog'],
            'opening_balance' => ['label' => 'Saldo inicial', 'type' => 'money'],
            'is_active' => ['label' => 'Activa', 'type' => 'checkbox'],
        ],
        'rules' => [
            'code' => ['required', 'string', 'max:40'],
            'name' => ['required', 'string', 'max:255'],
            'bank_id' => ['nullable', 'integer'],
            'bank_account_type_id' => ['nullable', 'integer'],
            'currency_id' => ['required', 'integer'],
            'opening_balance' => ['required', 'numeric'],
            'is_active' => ['nullable', 'boolean'],
        ],
    ],
    'cash-movements' => [
        'title' => 'Movimientos de caja',
        'section' => 'Tesorería',
        'model' => CashMovement::class,
        'display' => 'code',
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'movement_type_id' => ['label' => 'Tipo movimiento', 'type' => 'relation', 'model' => CashMovementType::class, 'display' => 'name', 'relation_name' => 'movementType'],
            'source_document_type' => ['label' => 'Tipo documento origen', 'type' => 'select', 'options' => ['sales_document' => 'Factura/Ingreso', 'expense_document' => 'Gasto/Egreso', 'payroll_record' => 'Remuneracion', 'legal_obligation' => 'Obligacion', 'other' => 'Otro']],
            'source_document_code' => ['label' => 'Codigo documento', 'type' => 'text'],
            'counterparty_name' => ['label' => 'Contraparte', 'type' => 'text'],
            'project_id' => ['label' => 'Proyecto', 'type' => 'relation', 'model' => Project::class, 'display' => 'name'],
            'movement_date' => ['label' => 'Fecha', 'type' => 'date'],
            'income' => ['label' => 'Ingreso', 'type' => 'money'],
            'expense' => ['label' => 'Egreso', 'type' => 'money'],
            'payment_method_id' => ['label' => 'Medio pago', 'type' => 'relation', 'model' => PaymentMethod::class, 'display' => 'name'],
            'cash_account_id' => ['label' => 'Cuenta', 'type' => 'relation', 'model' => CashAccount::class, 'display' => 'name'],
            'reference' => ['label' => 'Referencia', 'type' => 'text'],
            'status' => ['label' => 'Estado', 'type' => 'select', 'options' => ['posted' => 'Contabilizado', 'voided' => 'Anulado']],
        ],
        'rules' => [
            'code' => ['required', 'string', 'max:40'],
            'movement_type_id' => ['required', 'integer'],
            'source_document_type' => ['nullable', 'string', 'max:40'],
            'source_document_code' => ['nullable', 'string', 'max:40'],
            'counterparty_name' => ['nullable', 'string', 'max:255'],
            'project_id' => ['nullable', 'integer', 'exists:projects,id'],
            'movement_date' => ['required', 'date'],
            'income' => ['nullable', 'numeric', 'min:0'],
            'expense' => ['nullable', 'numeric', 'min:0'],
            'payment_method_id' => ['nullable', 'integer'],
            'cash_account_id' => ['nullable', 'integer', 'exists:cash_accounts,id'],
            'reference' => ['nullable', 'string', 'max:255'],
            'status' => ['required', 'string', 'max:20'],
        ],
    ],
    'payroll-records' => [
        'title' => 'Remuneraciones',
        'section' => 'Operación',
        'model' => PayrollRecord::class,
        'display' => 'code',
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'person_id' => ['label' => 'Persona', 'type' => 'relation', 'model' => Person::class, 'display' => 'name'],
            'project_id' => ['label' => 'Proyecto', 'type' => 'relation', 'model' => Project::class, 'display' => 'name'],
            'period_date' => ['label' => 'Periodo', 'type' => 'date'],
            'payment_date' => ['label' => 'Fecha pago', 'type' => 'date'],
            'base_salary' => ['label' => 'Base', 'type' => 'money'],
            'employee_retention' => ['label' => 'Retencion', 'type' => 'money'],
            'vacation_provision' => ['label' => 'Provision vacaciones', 'type' => 'money'],
            'employer_cost' => ['label' => 'Costo empresa', 'type' => 'money'],
            'net_pay' => ['label' => 'Liquido', 'type' => 'money'],
            'status' => ['label' => 'Estado', 'type' => 'text'],
        ],
        'rules' => [
            'code' => ['required', 'string', 'max:40'],
            'person_id' => ['required', 'integer', 'exists:people,id'],
            'project_id' => ['nullable', 'integer', 'exists:projects,id'],
            'period_date' => ['required', 'date'],
            'payment_date' => ['nullable', 'date'],
            'base_salary' => ['nullable', 'numeric', 'min:0'],
            'employee_retention' => ['nullable', 'numeric', 'min:0'],
            'vacation_provision' => ['nullable', 'numeric', 'min:0'],
            'employer_cost' => ['nullable', 'numeric', 'min:0'],
            'net_pay' => ['nullable', 'numeric', 'min:0'],
            'status' => ['nullable', 'string', 'max:20'],
        ],
    ],
    'legal-obligations' => [
        'title' => 'Obligaciones',
        'section' => 'Gestión',
        'model' => LegalObligation::class,
        'display' => 'code',
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'obligation_type_id' => ['label' => 'Tipo', 'type' => 'relation', 'model' => ObligationType::class, 'display' => 'name'],
            'organization_id' => ['label' => 'Organismo', 'type' => 'relation', 'model' => LegalOrganization::class, 'display' => 'name'],
            'period_date' => ['label' => 'Periodo', 'type' => 'date'],
            'due_date' => ['label' => 'Vencimiento', 'type' => 'date'],
            'estimated_amount' => ['label' => 'Estimado', 'type' => 'money'],
            'paid_amount' => ['label' => 'Pagado', 'type' => 'money', 'readonly' => true],
            'pending_amount' => ['label' => 'Pendiente', 'type' => 'money', 'readonly' => true],
            'status' => ['label' => 'Estado', 'type' => 'text', 'readonly' => true],
            'source_calculation' => ['label' => 'Fuente', 'type' => 'textarea'],
            'notes' => ['label' => 'Notas', 'type' => 'textarea'],
        ],
        'rules' => [
            'code' => ['required', 'string', 'max:40'],
            'obligation_type_id' => ['required', 'integer'],
            'organization_id' => ['nullable', 'integer'],
            'period_date' => ['required', 'date'],
            'due_date' => ['nullable', 'date'],
            'estimated_amount' => ['required', 'numeric', 'min:0'],
            'source_calculation' => ['nullable', 'string'],
            'notes' => ['nullable', 'string'],
        ],
    ],
    'budgets' => [
        'title' => 'Presupuestos',
        'section' => 'Gestión',
        'model' => Budget::class,
        'display' => 'period_date',
        'fields' => [
            'project_id' => ['label' => 'Proyecto', 'type' => 'relation', 'model' => Project::class, 'display' => 'name'],
            'scenario_id' => ['label' => 'Escenario', 'type' => 'relation', 'model' => Scenario::class, 'display' => 'name'],
            'period_date' => ['label' => 'Periodo', 'type' => 'date'],
            'revenue_budget' => ['label' => 'Ingreso presupuesto', 'type' => 'money'],
            'personnel_budget' => ['label' => 'Personal presupuesto', 'type' => 'money'],
            'other_direct_budget' => ['label' => 'Otros presupuesto', 'type' => 'money'],
            'legal_budget' => ['label' => 'Legal presupuesto', 'type' => 'money'],
            'other_indirect_budget' => ['label' => 'Indirectos presupuesto', 'type' => 'money'],
            'notes' => ['label' => 'Notas', 'type' => 'textarea'],
        ],
        'rules' => [
            'project_id' => ['nullable', 'integer', 'exists:projects,id'],
            'scenario_id' => ['nullable', 'integer', 'exists:scenarios,id'],
            'period_date' => ['required', 'date'],
            'revenue_budget' => ['required', 'numeric', 'min:0'],
            'personnel_budget' => ['required', 'numeric', 'min:0'],
            'other_direct_budget' => ['required', 'numeric', 'min:0'],
            'legal_budget' => ['required', 'numeric', 'min:0'],
            'other_indirect_budget' => ['required', 'numeric', 'min:0'],
            'notes' => ['nullable', 'string'],
        ],
    ],
    'scenarios' => [
        'title' => 'Escenarios',
        'section' => 'Gestión',
        'model' => Scenario::class,
        'display' => 'name',
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'name' => ['label' => 'Nombre', 'type' => 'text'],
            'sales_factor' => ['label' => 'Factor ventas', 'type' => 'decimal'],
            'cost_factor' => ['label' => 'Factor costos', 'type' => 'decimal'],
            'collection_delay_days' => ['label' => 'Retraso cobro dias', 'type' => 'number'],
            'new_hires_monthly' => ['label' => 'Nuevas contrataciones', 'type' => 'money'],
            'tariff_variation' => ['label' => 'Variacion tarifas', 'type' => 'decimal'],
            'description' => ['label' => 'Descripcion', 'type' => 'textarea'],
            'is_active' => ['label' => 'Activo', 'type' => 'checkbox'],
        ],
        'rules' => [
            'code' => ['required', 'string', 'max:40'],
            'name' => ['required', 'string', 'max:255'],
            'sales_factor' => ['required', 'numeric', 'min:0'],
            'cost_factor' => ['required', 'numeric', 'min:0'],
            'collection_delay_days' => ['required', 'integer'],
            'new_hires_monthly' => ['required', 'numeric'],
            'tariff_variation' => ['required', 'numeric'],
            'description' => ['nullable', 'string'],
            'is_active' => ['nullable', 'boolean'],
        ],
    ],
    'project-managers' => [
        'title' => 'Responsables',
        'section' => 'Administración',
        'breadcrumb_group' => 'Mantenedores',
        'model' => ProjectManager::class,
        'display' => 'name',
        'catalog' => true,
        'admin_only' => true,
        'usage' => [['model' => Project::class, 'column' => 'manager_id']],
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'name' => ['label' => 'Nombre', 'type' => 'text'],
            'description' => ['label' => 'Descripcion', 'type' => 'textarea'],
            'active' => ['label' => 'Activo', 'type' => 'checkbox'],
            'sort_order' => ['label' => 'Orden', 'type' => 'number'],
        ],
        'rules' => $catalogBaseRules,
    ],
    'cost-centers' => [
        'title' => 'Centros de costo',
        'section' => 'Administración',
        'breadcrumb_group' => 'Mantenedores',
        'model' => CostCenter::class,
        'display' => 'name',
        'catalog' => true,
        'admin_only' => true,
        'usage' => [
            ['model' => ProjectAssignment::class, 'column' => 'cost_center_id'],
            ['model' => TimeEntry::class, 'column' => 'cost_center_id'],
        ],
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'name' => ['label' => 'Nombre', 'type' => 'text'],
            'description' => ['label' => 'Descripcion', 'type' => 'textarea'],
            'active' => ['label' => 'Activo', 'type' => 'checkbox'],
            'sort_order' => ['label' => 'Orden', 'type' => 'number'],
        ],
        'rules' => $catalogBaseRules,
    ],
    'positions' => [
        'title' => 'Cargos',
        'section' => 'Administración',
        'breadcrumb_group' => 'Mantenedores',
        'model' => Position::class,
        'display' => 'name',
        'catalog' => true,
        'admin_only' => true,
        'usage' => [['model' => Person::class, 'column' => 'position_id']],
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'name' => ['label' => 'Nombre', 'type' => 'text'],
            'description' => ['label' => 'Descripcion', 'type' => 'textarea'],
            'active' => ['label' => 'Activo', 'type' => 'checkbox'],
            'sort_order' => ['label' => 'Orden', 'type' => 'number'],
        ],
        'rules' => $catalogBaseRules,
    ],
    'employment-modes' => [
        'title' => 'Modalidades',
        'section' => 'Administración',
        'breadcrumb_group' => 'Mantenedores',
        'model' => EmploymentMode::class,
        'display' => 'name',
        'catalog' => true,
        'admin_only' => true,
        'usage' => [['model' => Person::class, 'column' => 'employment_mode_id']],
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'name' => ['label' => 'Nombre', 'type' => 'text'],
            'description' => ['label' => 'Descripcion', 'type' => 'textarea'],
            'active' => ['label' => 'Activo', 'type' => 'checkbox'],
            'sort_order' => ['label' => 'Orden', 'type' => 'number'],
        ],
        'rules' => $catalogBaseRules,
    ],
    'contract-types' => [
        'title' => 'Tipos de contrato',
        'section' => 'Administración',
        'breadcrumb_group' => 'Mantenedores',
        'model' => ContractType::class,
        'display' => 'name',
        'catalog' => true,
        'admin_only' => true,
        'unique_scope' => ['domain'],
        'usage' => [
            ['model' => Person::class, 'column' => 'employment_contract_type_id'],
            ['model' => Project::class, 'column' => 'contract_type_id'],
        ],
        'fields' => [
            'domain' => ['label' => 'Dominio', 'type' => 'select', 'options' => ['employment' => 'Laboral', 'commercial' => 'Comercial']],
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'name' => ['label' => 'Nombre', 'type' => 'text'],
            'description' => ['label' => 'Descripcion', 'type' => 'textarea'],
            'active' => ['label' => 'Activo', 'type' => 'checkbox'],
            'sort_order' => ['label' => 'Orden', 'type' => 'number'],
        ],
        'rules' => array_merge($catalogBaseRules, ['domain' => ['required', 'string', 'in:employment,commercial']]),
    ],
    'banks' => [
        'title' => 'Bancos',
        'section' => 'Administración',
        'breadcrumb_group' => 'Mantenedores',
        'model' => Bank::class,
        'display' => 'name',
        'catalog' => true,
        'admin_only' => true,
        'usage' => [['model' => CashAccount::class, 'column' => 'bank_id']],
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'name' => ['label' => 'Nombre', 'type' => 'text'],
            'description' => ['label' => 'Descripcion', 'type' => 'textarea'],
            'active' => ['label' => 'Activo', 'type' => 'checkbox'],
            'sort_order' => ['label' => 'Orden', 'type' => 'number'],
        ],
        'rules' => $catalogBaseRules,
    ],
    'payment-methods' => [
        'title' => 'Medios de pago',
        'section' => 'Administración',
        'breadcrumb_group' => 'Mantenedores',
        'model' => PaymentMethod::class,
        'display' => 'name',
        'catalog' => true,
        'admin_only' => true,
        'usage' => [
            ['model' => CashMovement::class, 'column' => 'payment_method_id'],
            ['model' => PaymentTerm::class, 'column' => 'payment_method_id'],
        ],
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'name' => ['label' => 'Nombre', 'type' => 'text'],
            'description' => ['label' => 'Descripcion', 'type' => 'textarea'],
            'active' => ['label' => 'Activo', 'type' => 'checkbox'],
            'sort_order' => ['label' => 'Orden', 'type' => 'number'],
        ],
        'rules' => $catalogBaseRules,
    ],
    'expense-categories' => [
        'title' => 'Categorias de gasto',
        'section' => 'Administración',
        'breadcrumb_group' => 'Mantenedores',
        'model' => ExpenseCategory::class,
        'display' => 'name',
        'catalog' => true,
        'admin_only' => true,
        'usage' => [['model' => ExpenseDocument::class, 'column' => 'expense_category_id']],
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'name' => ['label' => 'Nombre', 'type' => 'text'],
            'description' => ['label' => 'Descripcion', 'type' => 'textarea'],
            'active' => ['label' => 'Activo', 'type' => 'checkbox'],
            'sort_order' => ['label' => 'Orden', 'type' => 'number'],
        ],
        'rules' => $catalogBaseRules,
    ],
    'expense-subcategories' => [
        'title' => 'Subcategorias de gasto',
        'section' => 'Administración',
        'breadcrumb_group' => 'Mantenedores',
        'model' => ExpenseSubcategory::class,
        'display' => 'name',
        'catalog' => true,
        'admin_only' => true,
        'unique_scope' => ['expense_category_id'],
        'usage' => [['model' => ExpenseDocument::class, 'column' => 'expense_subcategory_id']],
        'fields' => [
            'expense_category_id' => ['label' => 'Categoria', 'type' => 'relation', 'model' => ExpenseCategory::class, 'display' => 'name'],
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'name' => ['label' => 'Nombre', 'type' => 'text'],
            'description' => ['label' => 'Descripcion', 'type' => 'textarea'],
            'active' => ['label' => 'Activo', 'type' => 'checkbox'],
            'sort_order' => ['label' => 'Orden', 'type' => 'number'],
        ],
        'rules' => array_merge($catalogBaseRules, ['expense_category_id' => ['required', 'integer']]),
    ],
    'document-types' => [
        'title' => 'Tipos de documento',
        'section' => 'Administración',
        'breadcrumb_group' => 'Mantenedores',
        'model' => DocumentType::class,
        'display' => 'name',
        'catalog' => true,
        'admin_only' => true,
        'unique_scope' => ['domain'],
        'usage' => [
            ['model' => SalesDocument::class, 'column' => 'document_type_id'],
            ['model' => ExpenseDocument::class, 'column' => 'document_type_id'],
        ],
        'fields' => [
            'domain' => ['label' => 'Dominio', 'type' => 'select', 'options' => ['sales' => 'Ventas', 'expense' => 'Gastos']],
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'name' => ['label' => 'Nombre', 'type' => 'text'],
            'description' => ['label' => 'Descripcion', 'type' => 'textarea'],
            'active' => ['label' => 'Activo', 'type' => 'checkbox'],
            'sort_order' => ['label' => 'Orden', 'type' => 'number'],
        ],
        'rules' => array_merge($catalogBaseRules, ['domain' => ['required', 'string', 'in:sales,expense']]),
    ],
    'obligation-types' => [
        'title' => 'Tipos de obligación',
        'section' => 'Administración',
        'breadcrumb_group' => 'Mantenedores',
        'model' => ObligationType::class,
        'display' => 'name',
        'catalog' => true,
        'admin_only' => true,
        'usage' => [['model' => LegalObligation::class, 'column' => 'obligation_type_id']],
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'name' => ['label' => 'Nombre', 'type' => 'text'],
            'description' => ['label' => 'Descripcion', 'type' => 'textarea'],
            'active' => ['label' => 'Activo', 'type' => 'checkbox'],
            'sort_order' => ['label' => 'Orden', 'type' => 'number'],
        ],
        'rules' => $catalogBaseRules,
    ],
    'record-statuses' => [
        'title' => 'Estados principales',
        'section' => 'Administración',
        'breadcrumb_group' => 'Mantenedores',
        'model' => RecordStatus::class,
        'display' => 'name',
        'catalog' => true,
        'admin_only' => true,
        'unique_scope' => ['domain'],
        'usage' => [
            ['model' => Client::class, 'column' => 'client_status_id'],
            ['model' => Project::class, 'column' => 'project_status_id'],
            ['model' => Project::class, 'column' => 'billing_status_id'],
            ['model' => Person::class, 'column' => 'worker_status_id'],
            ['model' => ProjectAssignment::class, 'column' => 'assignment_status_id'],
        ],
        'fields' => [
            'domain' => ['label' => 'Dominio', 'type' => 'select', 'options' => ['client' => 'Clientes', 'project' => 'Proyectos', 'billing' => 'Facturación', 'worker' => 'Personal', 'assignment' => 'Asignaciones']],
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'name' => ['label' => 'Nombre', 'type' => 'text'],
            'description' => ['label' => 'Descripcion', 'type' => 'textarea'],
            'active' => ['label' => 'Activo', 'type' => 'checkbox'],
            'sort_order' => ['label' => 'Orden', 'type' => 'number'],
        ],
        'rules' => array_merge($catalogBaseRules, ['domain' => ['required', 'string', 'in:client,project,billing,worker,assignment']]),
    ],
    'client-types' => [
        'title' => 'Tipos de cliente',
        'section' => 'Administración',
        'breadcrumb_group' => 'Mantenedores',
        'model' => ClientType::class,
        'display' => 'name',
        'catalog' => true,
        'admin_only' => true,
        'usage' => [['model' => Client::class, 'column' => 'client_type_id']],
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'name' => ['label' => 'Nombre', 'type' => 'text'],
            'description' => ['label' => 'Descripcion', 'type' => 'textarea'],
            'active' => ['label' => 'Activo', 'type' => 'checkbox'],
            'sort_order' => ['label' => 'Orden', 'type' => 'number'],
        ],
        'rules' => $catalogBaseRules,
    ],
    'project-types' => [
        'title' => 'Tipos de proyecto',
        'section' => 'Administración',
        'breadcrumb_group' => 'Mantenedores',
        'model' => ProjectType::class,
        'display' => 'name',
        'catalog' => true,
        'admin_only' => true,
        'usage' => [['model' => Project::class, 'column' => 'project_type_id']],
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'name' => ['label' => 'Nombre', 'type' => 'text'],
            'description' => ['label' => 'Descripcion', 'type' => 'textarea'],
            'active' => ['label' => 'Activo', 'type' => 'checkbox'],
            'sort_order' => ['label' => 'Orden', 'type' => 'number'],
        ],
        'rules' => $catalogBaseRules,
    ],
    'payment-terms' => [
        'title' => 'Condiciones/Formas de pago',
        'section' => 'Administración',
        'breadcrumb_group' => 'Mantenedores',
        'model' => PaymentTerm::class,
        'display' => 'name',
        'catalog' => true,
        'admin_only' => true,
        'usage' => [
            ['model' => Client::class, 'column' => 'payment_term_id'],
            ['model' => Project::class, 'column' => 'payment_term_id'],
        ],
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'name' => ['label' => 'Nombre', 'type' => 'text'],
            'days' => ['label' => 'Días', 'type' => 'number'],
            'payment_method_id' => ['label' => 'Medio pago base', 'type' => 'relation', 'model' => PaymentMethod::class, 'display' => 'name'],
            'description' => ['label' => 'Descripcion', 'type' => 'textarea'],
            'active' => ['label' => 'Activo', 'type' => 'checkbox'],
            'sort_order' => ['label' => 'Orden', 'type' => 'number'],
        ],
        'rules' => array_merge($catalogBaseRules, [
            'days' => ['nullable', 'integer', 'min:0'],
            'payment_method_id' => ['nullable', 'integer'],
        ]),
    ],
    'currencies' => [
        'title' => 'Monedas',
        'section' => 'Administración',
        'breadcrumb_group' => 'Mantenedores',
        'model' => Currency::class,
        'display' => 'name',
        'catalog' => true,
        'admin_only' => true,
        'usage' => [['model' => CashAccount::class, 'column' => 'currency_id']],
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'name' => ['label' => 'Nombre', 'type' => 'text'],
            'description' => ['label' => 'Descripcion', 'type' => 'textarea'],
            'active' => ['label' => 'Activo', 'type' => 'checkbox'],
            'sort_order' => ['label' => 'Orden', 'type' => 'number'],
        ],
        'rules' => $catalogBaseRules,
    ],
    'activities' => [
        'title' => 'Actividades',
        'section' => 'Administración',
        'breadcrumb_group' => 'Mantenedores',
        'model' => Activity::class,
        'display' => 'name',
        'catalog' => true,
        'admin_only' => true,
        'usage' => [['model' => TimeEntry::class, 'column' => 'activity_id']],
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'name' => ['label' => 'Nombre', 'type' => 'text'],
            'description' => ['label' => 'Descripcion', 'type' => 'textarea'],
            'active' => ['label' => 'Activo', 'type' => 'checkbox'],
            'sort_order' => ['label' => 'Orden', 'type' => 'number'],
        ],
        'rules' => $catalogBaseRules,
    ],
    'approval-statuses' => [
        'title' => 'Estados de aprobación',
        'section' => 'Administración',
        'breadcrumb_group' => 'Mantenedores',
        'model' => ApprovalStatus::class,
        'display' => 'name',
        'catalog' => true,
        'admin_only' => true,
        'usage' => [['model' => TimeEntry::class, 'column' => 'approval_status_id']],
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'name' => ['label' => 'Nombre', 'type' => 'text'],
            'description' => ['label' => 'Descripcion', 'type' => 'textarea'],
            'active' => ['label' => 'Activo', 'type' => 'checkbox'],
            'sort_order' => ['label' => 'Orden', 'type' => 'number'],
        ],
        'rules' => $catalogBaseRules,
    ],
    'expense-types' => [
        'title' => 'Tipos de gasto',
        'section' => 'Administración',
        'breadcrumb_group' => 'Mantenedores',
        'model' => ExpenseType::class,
        'display' => 'name',
        'catalog' => true,
        'admin_only' => true,
        'usage' => [['model' => ExpenseDocument::class, 'column' => 'expense_type_id']],
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'name' => ['label' => 'Nombre', 'type' => 'text'],
            'description' => ['label' => 'Descripcion', 'type' => 'textarea'],
            'active' => ['label' => 'Activo', 'type' => 'checkbox'],
            'sort_order' => ['label' => 'Orden', 'type' => 'number'],
        ],
        'rules' => $catalogBaseRules,
    ],
    'cash-movement-types' => [
        'title' => 'Tipos de movimiento',
        'section' => 'Administración',
        'breadcrumb_group' => 'Mantenedores',
        'model' => CashMovementType::class,
        'display' => 'name',
        'catalog' => true,
        'admin_only' => true,
        'usage' => [['model' => CashMovement::class, 'column' => 'movement_type_id']],
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'name' => ['label' => 'Nombre', 'type' => 'text'],
            'description' => ['label' => 'Descripcion', 'type' => 'textarea'],
            'active' => ['label' => 'Activo', 'type' => 'checkbox'],
            'sort_order' => ['label' => 'Orden', 'type' => 'number'],
        ],
        'rules' => $catalogBaseRules,
    ],
    'bank-account-types' => [
        'title' => 'Tipos de cuenta bancaria',
        'section' => 'Administración',
        'breadcrumb_group' => 'Mantenedores',
        'model' => BankAccountType::class,
        'display' => 'name',
        'catalog' => true,
        'admin_only' => true,
        'usage' => [['model' => CashAccount::class, 'column' => 'bank_account_type_id']],
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'name' => ['label' => 'Nombre', 'type' => 'text'],
            'description' => ['label' => 'Descripcion', 'type' => 'textarea'],
            'active' => ['label' => 'Activo', 'type' => 'checkbox'],
            'sort_order' => ['label' => 'Orden', 'type' => 'number'],
        ],
        'rules' => $catalogBaseRules,
    ],
    'afps' => [
        'title' => 'AFP',
        'section' => 'Administración',
        'breadcrumb_group' => 'Mantenedores',
        'model' => Afp::class,
        'display' => 'name',
        'catalog' => true,
        'admin_only' => true,
        'active_column' => 'is_active',
        'usage' => [['model' => Person::class, 'column' => 'afp_id']],
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'name' => ['label' => 'Nombre', 'type' => 'text'],
            'is_active' => ['label' => 'Activo', 'type' => 'checkbox'],
        ],
        'rules' => [
            'code' => ['required', 'string', 'max:40'],
            'name' => ['required', 'string', 'max:255'],
            'is_active' => ['nullable', 'boolean'],
        ],
    ],
    'health-systems' => [
        'title' => 'Sistemas de salud',
        'section' => 'Administración',
        'breadcrumb_group' => 'Mantenedores',
        'model' => HealthSystem::class,
        'display' => 'name',
        'catalog' => true,
        'admin_only' => true,
        'usage' => [['model' => Person::class, 'column' => 'health_system_id']],
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'name' => ['label' => 'Nombre', 'type' => 'text'],
            'description' => ['label' => 'Descripcion', 'type' => 'textarea'],
            'active' => ['label' => 'Activo', 'type' => 'checkbox'],
            'sort_order' => ['label' => 'Orden', 'type' => 'number'],
        ],
        'rules' => $catalogBaseRules,
    ],
    'tax-regimes' => [
        'title' => 'Regímenes tributarios',
        'section' => 'Administración',
        'breadcrumb_group' => 'Mantenedores',
        'model' => TaxRegime::class,
        'display' => 'name',
        'catalog' => true,
        'admin_only' => true,
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'name' => ['label' => 'Nombre', 'type' => 'text'],
            'description' => ['label' => 'Descripcion', 'type' => 'textarea'],
            'active' => ['label' => 'Activo', 'type' => 'checkbox'],
            'sort_order' => ['label' => 'Orden', 'type' => 'number'],
        ],
        'rules' => $catalogBaseRules,
    ],
    'legal-organizations' => [
        'title' => 'Organismos',
        'section' => 'Administración',
        'breadcrumb_group' => 'Mantenedores',
        'model' => LegalOrganization::class,
        'display' => 'name',
        'catalog' => true,
        'admin_only' => true,
        'usage' => [['model' => LegalObligation::class, 'column' => 'organization_id']],
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'name' => ['label' => 'Nombre', 'type' => 'text'],
            'description' => ['label' => 'Descripcion', 'type' => 'textarea'],
            'active' => ['label' => 'Activo', 'type' => 'checkbox'],
            'sort_order' => ['label' => 'Orden', 'type' => 'number'],
        ],
        'rules' => $catalogBaseRules,
    ],
    'occupational-insurance-entities' => [
        'title' => 'Mutualidades',
        'section' => 'Administración',
        'breadcrumb_group' => 'Mantenedores',
        'model' => OccupationalInsuranceEntity::class,
        'display' => 'name',
        'catalog' => true,
        'admin_only' => true,
        'fields' => [
            'code' => ['label' => 'Codigo', 'type' => 'text'],
            'name' => ['label' => 'Nombre', 'type' => 'text'],
            'description' => ['label' => 'Descripcion', 'type' => 'textarea'],
            'active' => ['label' => 'Activo', 'type' => 'checkbox'],
            'sort_order' => ['label' => 'Orden', 'type' => 'number'],
        ],
        'rules' => $catalogBaseRules,
    ],
];
