<?php
namespace App\Http\Controllers;
use App\Models\Project; use App\Models\ProjectBillingMilestone; use App\Services\ProjectBillingMilestoneService; use DomainException; use Illuminate\Http\JsonResponse; use Illuminate\Http\RedirectResponse; use Illuminate\Http\Request;
class ProjectBillingMilestoneController extends Controller {
    public function __construct(private readonly ProjectBillingMilestoneService $milestones) {}
    public function store(Request $request, Project $project): RedirectResponse { return $this->save($request, $project); }
    public function update(Request $request, Project $project, ProjectBillingMilestone $milestone): RedirectResponse { $this->owned($request, $project); $this->belongsToProject($project, $milestone); return $this->save($request, $project, $milestone); }
    public function destroy(Request $request, Project $project, ProjectBillingMilestone $milestone): RedirectResponse { $this->owned($request, $project); $this->belongsToProject($project, $milestone); try { $this->milestones->delete($milestone); return back()->with('status', 'Hito eliminado.'); } catch (DomainException $e) { return back()->withErrors(['milestone' => $e->getMessage()]); } }
    public function issue(Request $request, Project $project, ProjectBillingMilestone $milestone): RedirectResponse { $this->owned($request, $project); $this->belongsToProject($project, $milestone); $data = $request->validate(['issue_date' => ['required','date'], 'taxable' => ['nullable','boolean']]); try { $document = $this->milestones->issue($milestone, $data['issue_date'], (bool) ($data['taxable'] ?? true)); return redirect()->route('operational.show', ['resource' => 'sales-documents', 'record' => $document->id])->with('status', 'Borrador de factura por hito generado.'); } catch (DomainException $e) { return back()->withErrors(['milestone' => $e->getMessage()]); } }
    public function preview(Request $request, Project $project, ProjectBillingMilestone $milestone): JsonResponse { $this->owned($request, $project); $this->belongsToProject($project, $milestone); $data = $request->validate(['issue_date' => ['required','date'], 'taxable' => ['nullable','boolean']]); try { $taxable = (bool) ($data['taxable'] ?? true); $preview = $this->milestones->preview($milestone, $data['issue_date'], $taxable); $amounts = $preview['amounts']; if (! $taxable) { $amounts['vat_rate'] = 0; $amounts['vat_amount'] = 0; $amounts['gross_amount'] = $amounts['net_amount']; } return response()->json(['milestone' => ['id' => $milestone->id, 'sequence' => $milestone->sequence, 'name' => $milestone->name, 'percentage' => (float) $milestone->percentage, 'planned_invoice_date' => optional($milestone->planned_invoice_date)->toDateString()], 'contractual_amount' => $preview['contractual_amount'], 'contractual_currency' => $preview['contractual_currency'], 'conversion' => $preview['conversion'], 'net_amount' => $amounts['net_amount'], 'vat_rate' => $amounts['vat_rate'], 'vat_amount' => $amounts['vat_amount'], 'gross_amount' => $amounts['gross_amount'], 'due_date' => $preview['due_date']?->toDateString(), 'projected_collection_date' => $preview['due_date']?->toDateString()]); } catch (DomainException $e) { return response()->json(['message' => $e->getMessage()], 422); } }
    private function save(Request $request, Project $project, ?ProjectBillingMilestone $milestone = null): RedirectResponse { $this->owned($request, $project); $data = $request->validate(['sequence' => ['required','integer','min:1'], 'name' => ['required','string','max:255'], 'planned_invoice_date' => ['nullable','date'], 'percentage' => ['required','numeric','gt:0','max:100'], 'notes' => ['nullable','string']]); try { $this->milestones->save($project, $data, $milestone); return back()->with('status', $milestone ? 'Hito actualizado.' : 'Hito agregado.'); } catch (DomainException $e) { return back()->withInput()->withErrors(['milestone' => $e->getMessage()]); } }
    private function owned(Request $request, Project $project): void { abort_unless($project->company_id === $request->user()->company_id, 404); }
    private function belongsToProject(Project $project, ProjectBillingMilestone $milestone): void { abort_unless($milestone->project_id === $project->id && $milestone->company_id === $project->company_id, 404); }
}
