<?php
namespace App\Http\Controllers;
use App\Models\Project; use App\Models\ProjectBillingMilestone; use App\Services\ProjectBillingMilestoneService; use DomainException; use Illuminate\Http\RedirectResponse; use Illuminate\Http\Request;
class ProjectBillingMilestoneController extends Controller {
    public function __construct(private readonly ProjectBillingMilestoneService $milestones) {}
    public function store(Request $request, Project $project): RedirectResponse { return $this->save($request, $project); }
    public function update(Request $request, Project $project, ProjectBillingMilestone $milestone): RedirectResponse { $this->owned($request, $project); abort_unless($milestone->project_id === $project->id, 404); return $this->save($request, $project, $milestone); }
    public function destroy(Request $request, Project $project, ProjectBillingMilestone $milestone): RedirectResponse { $this->owned($request, $project); abort_unless($milestone->project_id === $project->id, 404); try { $this->milestones->delete($milestone); return back()->with('status', 'Hito eliminado.'); } catch (DomainException $e) { return back()->withErrors(['milestone' => $e->getMessage()]); } }
    public function issue(Request $request, Project $project, ProjectBillingMilestone $milestone): RedirectResponse { $this->owned($request, $project); abort_unless($milestone->project_id === $project->id, 404); $data = $request->validate(['issue_date' => ['required','date'], 'taxable' => ['nullable','boolean']]); try { $document = $this->milestones->issue($milestone, $data['issue_date'], (bool) ($data['taxable'] ?? true)); return redirect()->route('operational.show', ['resource' => 'sales-documents', 'record' => $document->id])->with('status', 'Borrador de factura por hito generado.'); } catch (DomainException $e) { return back()->withErrors(['milestone' => $e->getMessage()]); } }
    private function save(Request $request, Project $project, ?ProjectBillingMilestone $milestone = null): RedirectResponse { $this->owned($request, $project); $data = $request->validate(['sequence' => ['required','integer','min:1'], 'name' => ['required','string','max:255'], 'planned_invoice_date' => ['nullable','date'], 'percentage' => ['required','numeric','gt:0','max:100'], 'notes' => ['nullable','string']]); try { $this->milestones->save($project, $data, $milestone); return back()->with('status', $milestone ? 'Hito actualizado.' : 'Hito agregado.'); } catch (DomainException $e) { return back()->withInput()->withErrors(['milestone' => $e->getMessage()]); } }
    private function owned(Request $request, Project $project): void { abort_unless($project->company_id === $request->user()->company_id, 404); }
}
