@extends('layouts.app')

@section('content')
<div class="page-header"><div><h1 class="page-title">Cartolas bancarias</h1><p class="page-subtitle">Importe CSV y confirme manualmente vínculos 1:1 con movimientos contabilizados.</p></div></div>

<div class="alert alert-secondary app-panel">La importación no crea ni modifica movimientos de caja. Las sugerencias son asistidas: el matching siempre requiere confirmación manual.</div>

<div class="app-panel p-3 mb-4">
    <form method="GET" class="row g-3 align-items-end">
        <div class="col-md-5"><label class="form-label" for="cash-account">Cuenta CLP</label><select id="cash-account" class="form-select" name="cash_account_id"><option value="">Seleccione</option>@foreach ($accounts as $account)<option value="{{ $account->id }}" @selected($selected?->id === $account->id)>{{ $account->name }} · {{ $account->code }}</option>@endforeach</select></div>
        <div class="col-md-3"><label class="form-label" for="statement-status">Estado línea</label><select id="statement-status" class="form-select" name="status"><option value="">Todos</option>@foreach (['unmatched' => 'Sin matching', 'matched' => 'Matched', 'ignored' => 'Ignorada'] as $value => $label)<option value="{{ $value }}" @selected(request('status') === $value)>{{ $label }}</option>@endforeach</select></div>
        <div class="col-md-2"><button class="btn btn-outline-primary" type="submit">Ver cartolas</button></div>
    </form>
    @if ($selected)
        <hr>
        <form method="POST" action="{{ route('bank-statements.import') }}" enctype="multipart/form-data" class="row g-3 align-items-end">
            @csrf
            <input type="hidden" name="cash_account_id" value="{{ $selected->id }}">
            <div class="col-md-6"><label class="form-label" for="statement">CSV de cartola</label><input id="statement" class="form-control" type="file" name="statement" accept=".csv,text/csv" required><div class="form-text">Formato canónico: fecha, descripcion, referencia, ingreso, egreso. Máximo 2 MB.</div></div>
            <div class="col-md-3"><button class="btn btn-primary" type="submit">Importar CSV</button></div>
        </form>
    @endif
</div>

@if ($selected && $summary)
<div class="row g-3 mb-4">
    <div class="col-md-3"><div class="app-panel p-3"><div class="small text-muted">Movimientos sistema</div><div class="fs-4">{{ $summary['system'] }}</div><div class="small text-muted">Sin matching: {{ $summary['unmatched_system'] }}</div></div></div>
    <div class="col-md-3"><div class="app-panel p-3"><div class="small text-muted">Líneas cartola</div><div class="fs-4">{{ $summary['lines'] }}</div><div class="small text-muted">Sin matching: {{ $summary['unmatched_bank'] }}</div></div></div>
    <div class="col-md-3"><div class="app-panel p-3"><div class="small text-muted">Matched</div><div class="fs-4">{{ $summary['matched'] }}</div><div class="small text-muted">Ignoradas: {{ $summary['ignored'] }}</div></div></div>
    <div class="col-md-3"><div class="app-panel p-3"><div class="small text-muted">Total banco importado</div><div class="fs-4 amount-cell">{{ \App\Support\UiFormatter::formatMoney($summary['bank_total']) }}</div><a class="small" href="{{ route('bank-reconciliation.index', ['cash_account_id' => $selected->id]) }}">Ver conciliación bancaria</a></div></div>
</div>
@endif

@if ($selectedLine)
<div class="app-panel section-card mb-4"><div class="section-card-header"><h2 class="section-card-title">Sugerencias para línea #{{ $selectedLine->id }}</h2></div><div class="p-3"><div class="mb-3"><strong>{{ \App\Support\UiFormatter::formatDate($selectedLine->transaction_date) }}</strong> · {{ $selectedLine->description }} · {{ $selectedLine->direction === 'income' ? 'Ingreso' : 'Egreso' }} {{ \App\Support\UiFormatter::formatMoney($selectedLine->amount) }}</div><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Fecha</th><th>Movimiento</th><th>Referencia</th><th>Contraparte</th><th class="text-end">Monto</th><th>Score</th><th>Acción</th></tr></thead><tbody>@forelse ($suggestions as $movement)<tr><td>{{ \App\Support\UiFormatter::formatDate($movement->movement_date) }}</td><td>{{ $movement->code }}</td><td>{{ $movement->reference ?: '—' }}</td><td>{{ $movement->counterparty_name ?: '—' }}</td><td class="text-end">{{ \App\Support\UiFormatter::formatMoney($selectedLine->direction === 'income' ? $movement->income : $movement->expense) }}</td><td>{{ $movement->bank_statement_score }}</td><td><form method="POST" action="{{ route('bank-statements.match') }}">@csrf<input type="hidden" name="bank_statement_line_id" value="{{ $selectedLine->id }}"><input type="hidden" name="cash_movement_id" value="{{ $movement->id }}"><input type="hidden" name="score" value="{{ $movement->bank_statement_score }}"><button class="btn btn-sm btn-primary" type="submit">Confirmar matching</button></form></td></tr>@empty<tr><td colspan="7" class="text-center text-muted">No hay candidatos compatibles. Puede dejar la línea sin matching o ignorarla con motivo.</td></tr>@endforelse</tbody></table></div></div></div>
@endif

<div class="app-panel section-card mb-4"><div class="section-card-header"><h2 class="section-card-title">Líneas de cartola</h2></div><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Fecha</th><th>Descripción / referencia</th><th>Importación</th><th class="text-end">Ingreso</th><th class="text-end">Egreso</th><th>Estado</th><th>Acción</th></tr></thead><tbody>@forelse ($lines as $line)<tr><td>{{ \App\Support\UiFormatter::formatDate($line->transaction_date) }}</td><td>{{ $line->description }}<div class="small text-muted">{{ $line->reference ?: 'Sin referencia' }}</div></td><td>{{ $line->bankStatementImport?->original_filename }}</td><td class="text-end">@if ($line->direction === 'income'){{ \App\Support\UiFormatter::formatMoney($line->amount) }}@endif</td><td class="text-end">@if ($line->direction === 'expense'){{ \App\Support\UiFormatter::formatMoney($line->amount) }}@endif</td><td>@if ($line->status === 'matched')<span class="badge text-bg-success">Matched</span><div class="small text-muted">{{ $line->activeMatch?->cashMovement?->code }}</div>@elseif ($line->status === 'ignored')<span class="badge text-bg-secondary">Ignorada</span><div class="small text-muted">{{ $line->ignore_reason }}</div>@else<span class="badge text-bg-warning">Sin matching</span>@endif</td><td>@if ($line->status === 'unmatched')<a class="btn btn-sm btn-outline-primary mb-1" href="{{ route('bank-statements.index', ['cash_account_id' => $selected?->id, 'line_id' => $line->id]) }}">Ver sugerencias</a><form method="POST" action="{{ route('bank-statements.ignore', $line->id) }}" class="d-flex gap-1">@csrf<input class="form-control form-control-sm" name="ignore_reason" maxlength="2000" placeholder="Motivo obligatorio" required><button class="btn btn-sm btn-outline-secondary" type="submit">Ignorar</button></form>@elseif ($line->status === 'matched')<form method="POST" action="{{ route('bank-statements.reverse', $line->activeMatch?->id) }}" class="d-flex gap-1">@csrf<input class="form-control form-control-sm" name="reversal_reason" maxlength="2000" placeholder="Motivo reversión" required><button class="btn btn-sm btn-outline-danger" type="submit">Revertir</button></form>@else<span class="text-muted">Solo lectura</span>@endif</td></tr>@empty<tr><td colspan="7" class="text-center text-muted">Sin líneas de cartola para la cuenta y filtros seleccionados.</td></tr>@endforelse</tbody></table></div>{{ $lines->links() }}</div>

<div class="app-panel section-card"><div class="section-card-header"><h2 class="section-card-title">Importaciones recientes</h2></div><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Archivo</th><th>Período</th><th>Filas</th><th>Importado por</th><th>Estado</th></tr></thead><tbody>@forelse ($imports as $import)<tr><td>{{ $import->original_filename }}</td><td>{{ \App\Support\UiFormatter::formatDate($import->statement_from) }} · {{ \App\Support\UiFormatter::formatDate($import->statement_to) }}</td><td>{{ $import->row_count }}</td><td>{{ $import->importedBy?->name ?: 'Sistema' }}</td><td>{{ $import->status }}</td></tr>@empty<tr><td colspan="5" class="text-center text-muted">Sin cartolas importadas.</td></tr>@endforelse</tbody></table></div></div>
@endsection
